import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {buildCalcuttaModel,calcuttaPublicationRecords,deriveCalcuttaRoundResults} from '../lib/calcutta.js';
const predecessor=await import('data:text/javascript;base64,'+Buffer.from(execFileSync('git',['show','078fbfa90e4b1a2b9f01b9e3cc085c33ce271fb5:lib/calcutta.js'])).toString('base64'));
function input(ids,format='SC',tie=false){const round={BB:1,SC:2,SI:3}[format];return {year:2026,updatedAt:'2026-01-01T00:00:00.000Z',players:Object.fromEntries(['P01','P02','P03','P04'].map(id=>[id,{id,name:id}])),purchases:ids.map(id=>({Year:2026,'Golfer Player ID':id,'Purchase Price':1})),ownership:ids.map(id=>({Year:2026,'Golfer Player ID':id,'Owner Player ID':'P12','Ownership %':100})),pointStructure:[1,2,3,4].map(Place=>({Year:2026,Place,[`Round ${round} Award`]:100/Place})),payoutStructure:[1,2,3,4].map(Place=>({Year:2026,Place,[`Round ${round} Award %`]:20/Place})),roundResults:format==='SC'?[['P01,P02',70],['P03,P04',tie?70:72]].map(([ids,net])=>({Year:2026,Round:round,Format:format,'Player IDs':ids,'Net Score':net,'Gross Score':net})):['P01','P02','P03','P04'].map((id,i)=>({Year:2026,Round:round,Format:format,'Player ID':id,'Net Score':70+(tie?0:i),'Gross Score':70+i}))};}
test('exact predecessor rejects purchased P01 with unpurchased Scramble P02 with null-ranking TypeError',()=>assert.throws(()=>predecessor.calcuttaPublicationRecords(input(['P01'])),e=>e instanceof TypeError&&/null.*map/.test(e.message)));
for(const ids of [['P01','P02'],['P01'],['P02'],[],['P01','P04']]) for(const tie of [false,true]) test(`SC purchase set ${ids.join(',')||'none'}, tie ${tie}: context and financial eligibility separate`,()=>{const data=input(ids,'SC',tie),before=JSON.stringify(data);const publication=calcuttaPublicationRecords(data);assert.equal(JSON.stringify(data),before);assert.deepEqual(publication.standings.map(r=>r['Player ID']).sort(),[...ids].sort());if(!ids.length){assert.deepEqual(publication,{roundResults:[],standings:[]});return;}const model=buildCalcuttaModel({...data,roundResults:deriveCalcuttaRoundResults(data)});const read=buildCalcuttaModel({...data,roundResults:publication.roundResults,standings:publication.standings});assert.equal(model.pot,ids.length);assert.deepEqual(model.golfers.map(g=>g.playerId).sort(),[...ids].sort());assert.deepEqual(read.golfers,model.golfers);assert.deepEqual(read.portfolios,model.portfolios);for(const golfer of model.golfers){assert.equal(golfer.rounds[2].points,ids.includes('P04')?(tie?37.5:(golfer.playerId==='P04'?25:50)):50);assert.ok(golfer.owners.every(o=>o.ownerId==='P12'));} });
for(const format of ['BB','SI'])test(`${format} partial purchase preserves existing individual policy`,()=>{const data=input(['P01','P03'],format,true);assert.deepEqual(calcuttaPublicationRecords(data),predecessor.calcuttaPublicationRecords(data));});
test('malformed canonical Scramble pairing produces typed failure, never empty payout',()=>{const data=input(['P01']);data.roundResults=deriveCalcuttaRoundResults(data).filter(r=>r['Player ID']!=='P02');assert.throws(()=>buildCalcuttaModel(data),e=>e.code==='CALCUTTA_COMPETITIVE_PAIRING_INVALID');});
test('purchased-only ownership, tie replay and existing failure classification',async()=>{const {classifyDerivedFailure}=await import('../lib/score-derived-worker.js');const data=input(['P01']);data.ownership.push({Year:2026,'Golfer Player ID':'P02','Owner Player ID':'P13','Ownership %':100});const before=JSON.stringify(data),result=calcuttaPublicationRecords(data);assert.deepEqual(calcuttaPublicationRecords(data),result);const model=buildCalcuttaModel({...data,roundResults:deriveCalcuttaRoundResults(data)});assert.equal(model.portfolios.length,1);assert.equal(model.portfolios[0].ownerId,'P12');assert.equal(model.golfers.length,1);assert.equal(model.golfers[0].rounds[2].payoutPercent,.1);assert.equal(model.golfers[0].currentPayoutValue,.1);assert.equal(JSON.stringify(data),before);assert.equal(classifyDerivedFailure(Object.assign(new Error('safe'),{code:'CALCUTTA_COMPETITIVE_PAIRING_INVALID'})).classification,'TERMINAL');assert.equal(classifyDerivedFailure(Object.assign(new Error('safe'),{code:'ECONNRESET'})).classification,'RETRYABLE');});
