import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {fixture} from './calcutta-management.test.mjs';
import {predecessor,canonicalEqual} from '../lib/calcutta-management-model.js';
const enabled=process.execArgv.includes('--conditions=react-server');
if(!enabled)test('clear server-only contracts',()=>{const p=spawnSync(process.execPath,['--conditions=react-server','--test',import.meta.filename],{encoding:'utf8'});assert.equal(p.status,0,p.stdout+p.stderr);});
const st=enabled?test:()=>{};
const {manageCalcutta}=enabled?await import('../lib/calcutta-management-server.js'):{};
const actor={actorAuthUserId:'11000000-0000-4000-8000-000000000001',actorPlayerId:'P1'};
function harness(){let m={...fixture(),auction_revision:1,auction_fingerprint:'b'.repeat(64),publication_revision:2,purchases:[{player_id:'P2',purchase_price:'100'}],ownership:[{player_id:'P2',owner_player_id:'P3',ownership_fraction:'0.5'},{player_id:'P2',owner_player_id:'P4',ownership_fraction:'0.5'}]};const history=structuredClone(m),requests=[],receipts=new Map();let loseReply=false;const options={scoringDispatchContext:{runtime:{tournamentId:'2026'}},dependencies:{read:async()=>({data:{...m,predecessor_purchases:history.purchases,predecessor_ownership:history.ownership,predecessor_auction_fingerprint:history.auction_fingerprint}}),clear:async p=>{requests.push(p);if(receipts.has(p.requestFingerprint))return receipts.get(p.requestFingerprint);assert.equal(p.expectedAuctionRevision,m.auction_revision);m={...m,purchases:[],ownership:[],auction_revision:2,auction_fingerprint:'c'.repeat(64),publication_revision:3};const receipt={ok:true,code:'PRODUCTION_CALCUTTA_V1_ENTRY_CLEARED',cleared_player_id:p.playerId,publication_state:'UNPUBLISHED',configuration_revision:2,configuration_fingerprint:m.configuration_fingerprint,auction_revision:2,auction_fingerprint:m.auction_fingerprint,publication_revision:3};receipts.set(p.requestFingerprint,receipt);if(loseReply)throw Error('timeout after commit');return receipt;}}};return{get model(){return m},set model(v){m=v},history,requests,options,set loseReply(v){loseReply=v}};}
st('clear readback proves only selected entry removed; uncertain delivery reuses immutable predecessor',async()=>{const h=harness(),input={...predecessor(h.model),playerId:'P2',requestFingerprint:'d'.repeat(64)};h.loseReply=true;await assert.rejects(manageCalcutta('management-clear-entry',input,actor,h.options),/timeout/);h.loseReply=false;const r=await manageCalcutta('management-clear-entry',input,actor,h.options);assert.equal(r.readbackVerified,true);assert.deepEqual(r.data.purchases,[]);assert.deepEqual(h.requests[0],h.requests[1]);assert.equal(h.history.purchases[0].purchase_price,'100');});
st('clear rejects wrong golfer, tournament, published and forged predecessor before mutation',async()=>{for(const change of [{playerId:'UNKNOWN'},{expectedTournamentId:'2099'},{expectedAuctionFingerprint:'f'.repeat(64)}]){const h=harness();await assert.rejects(manageCalcutta('management-clear-entry',{...predecessor(h.model),playerId:'P2',requestFingerprint:'d'.repeat(64),...change},actor,h.options));assert.equal(h.requests.length,0);}const h=harness();h.model={...h.model,publication_state:'PUBLISHED'};await assert.rejects(manageCalcutta('management-clear-entry',{...predecessor(h.model),playerId:'P2',requestFingerprint:'d'.repeat(64)},actor,h.options),/Unpublish/);assert.equal(h.requests.length,0);});
st('clear requires semantic receipt and matching canonical readback',async()=>{for(const type of ['receipt','readback']){const h=harness(),input={...predecessor(h.model),playerId:'P2',requestFingerprint:'d'.repeat(64)};if(type==='receipt')h.options.dependencies.clear=async()=>({ok:true});else{const clear=h.options.dependencies.clear;h.options.dependencies.clear=async p=>{const r=await clear(p);h.model={...h.model,purchases:h.history.purchases};return r;};}await assert.rejects(manageCalcutta('management-clear-entry',input,actor,h.options),/receipt|readback/);}});
