import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {loadDirectorSource,elements,text} from './fixtures/director-behavior.mjs';
import * as model from '../lib/calcutta-management-model.js';
import {fixture} from './calcutta-management.test.mjs';
import {createClientMutationOperationIdentityRegistry} from '../lib/client-mutation-operation-identity.js';
function stateHooks(){const cells=[];let cursor=0;return{cells,reset(){cursor=0},hooks:{useState(v){const i=cursor++;if(!(i in cells))cells[i]=typeof v==='function'?v():v;return[cells[i],v=>{cells[i]=typeof v==='function'?v(cells[i]):v}]},useRef(v){const i=cursor++;if(!(i in cells))cells[i]={current:v};return cells[i]},useCallback:fn=>fn,useMemo:fn=>fn(),useEffect:()=>{}}};}
const css=new Proxy({},{get:(_,k)=>String(k)});
async function editorHarness(transport){const h=stateHooks();const exports=await loadDirectorSource('app/admin/director/CalcuttaManagementEditor.js',{react:h.hooks,'../../../lib/calcutta-management-model.js':model,'./calcutta-management.module.css':css});return {...h,exports,render(){h.reset();return exports.default({transport});}};}
const button=(tree,label)=>elements(tree).find(e=>e.type==='button'&&text(e)===label);
function field(tree,label,value){const e=elements(tree).find(e=>e.props?.label===label);assert.ok(e,label);e.props.onChange(value);}
function list(tree){return elements(tree).find(e=>e.props?.rows&&e.props?.onEdit);}
const fx=fixture();
test('all 24 canonical rows, revision 2/auction 0, exact money, owner validity',async()=>{const h=await editorHarness();h.cells[0]=fx;h.cells[1]=model.configurationDraft(fx);const tree=h.render();assert.equal(list(tree).props.rows.length,24);assert.match(text(tree),/Configuration revision 2/);assert.match(text(tree),/Auction revision 0/);assert.equal(h.exports.money('1200.000000000000000001'),'$1,200.000000000000000001');for(const owners of [[{buyerId:'unknown',percentage:'100'}],[{buyerId:'P1',percentage:'50'},{buyerId:'P1',percentage:'50'}],[{buyerId:'P1',percentage:'0'},{buyerId:'P2',percentage:'100'}]])assert.equal(h.exports.entryStatus({playerId:'P1',purchasePrice:'1',owners},fx.players).status,'INVALID');assert.equal(h.exports.entryStatus({playerId:'P1',purchasePrice:'1',owners:[{buyerId:'P1',percentage:'75'}]},fx.players).status,'INCOMPLETE');});
test('draft attention filters retain saved rows; review summary uses only saved authority',async()=>{const h=await editorHarness();h.cells[0]=fx;h.cells[1]=model.configurationDraft(fx);list(h.render()).props.onEdit('P2');field(h.render(),'Purchase Price (USD)','1200');button(h.render(),'+ Add Owner').props.onClick();const owner=elements(h.render()).find(e=>e.props?.index===0&&e.props?.players);owner.props.onChange('P1');field(h.render(),'Ownership %','75');const filter=elements(h.render()).find(e=>e.type==='select'&&e.props.value==='ALL');filter.props.onChange({target:{value:'NEEDS ATTENTION'}});assert.equal(list(h.render()).props.rows.length,1);assert.equal(list(h.render()).props.rows[0].status,'INCOMPLETE');assert.equal(button(h.render(),'Review Entry Changes').props.disabled,true);assert.equal(button(h.render(),'Review Auction').props.disabled,true);filter.props.onChange({target:{value:'ALL'}});assert.equal(list(h.render()).props.rows.length,24);assert.equal(fx.purchases.length,0);});
test('Save & Next waits for verified receipt, exact fractions and no publish/calculate',async()=>{let release,seen;const h=await editorHarness(async(action,payload)=>{seen={action,payload};return new Promise(r=>release=r)});h.cells[0]=fx;h.cells[1]=model.configurationDraft(fx);list(h.render()).props.onEdit('P1');field(h.render(),'Purchase Price (USD)','1200.01');button(h.render(),'+ Add Owner').props.onClick();elements(h.render()).find(e=>e.props?.index===0&&e.props?.players).props.onChange('P2');field(h.render(),'Ownership %','100');button(h.render(),'Review Entry Changes').props.onClick();elements(h.render()).find(e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});const saving=button(h.render(),'Save & Next').props.onClick();assert.equal(seen.action,'management-entry');assert.equal(seen.payload.expectedConfigurationRevision,2);assert.equal(seen.payload.entry.purchasePrice,'1200.01');assert.equal(h.cells[2].playerId,'P1');const data={...fx,...model.mergeEntry(fx,model.entryPayload(seen.payload.entry,fx.players)),auction_revision:1};release({data,readbackVerified:true,receipt:{ok:true}});await saving;assert.equal(h.cells[2].playerId,'P2');assert.match(text(h.render()),/P1|Player 1 saved/);assert.match(text(h.render()),/Still UNPUBLISHED/);});
test('uncertain save retains same request and player; no advance before semantic receipt',async()=>{const requests=[];const h=await editorHarness(async(a,p)=>{requests.push(p);return{readbackVerified:false}});h.cells[0]=fx;h.cells[1]=model.configurationDraft(fx);h.cells[2]={playerId:'P1',purchasePrice:'25',owners:[{buyerId:'P1',percentage:'100'}]};button(h.render(),'Review Entry Changes').props.onClick();elements(h.render()).find(e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});await button(h.render(),'Save & Next').props.onClick();assert.equal(h.cells[2].playerId,'P1');await button(h.render(),'Retry same saved request').props.onClick();assert.equal(requests[0],requests[1]);assert.equal(h.cells[2].playerId,'P1');});
test('Save & Next skips entered golfers, wraps, and stops after complete roster',async()=>{const h=await editorHarness();const m={...fx,purchases:[{player_id:'P2'}]};assert.equal(h.exports.nextUnentered(m,'P1').player_id,'P3');assert.equal(h.exports.nextUnentered(m,'P24').player_id,'P1');assert.equal(h.exports.nextUnentered({...m,purchases:fx.players},'P1'),undefined);});
async function cardHarness(){const h=stateHooks();const deps={react:h.hooks,'../../../lib/client-mutation-operation-identity.js':{createClientMutationOperationIdentityRegistry},'../../../lib/net-skins-configuration-readiness.js':{},'./production-director.module.css':css,'./calcutta-management.module.css':css};for(const n of ['ProductionDraftEditor','ProductionGuideEditor','ProductionPredictionSettingsEditor','ProductionNetSkinsEntries','ProductionOddsSnapshotReview','ProductionRoundScoringControls'])deps[`./${n}.js`]=()=>null;deps['./CalcuttaManagementEditor.js']={default:()=>null,FinancialSafety:()=>null,money:v=>`$${v}`};const {CalcuttaCard}=await loadDirectorSource('app/admin/director/ProductionDirectorOperations.js',deps);const state={state:'AUCTION_COMPLETE',configurationRevision:2,configurationFingerprint:'a'.repeat(64),auctionRevision:3,auctionFingerprint:'b'.repeat(64),publicationRevision:4,publicationState:'UNPUBLISHED',published:false};const data={publications:{calcutta:state},privateOperations:{calcutta:{...state,configuration:null,auction:{pot:'1200',purchaseCount:1}}}};return{...h,data,render(draftPending=false){h.reset();return CalcuttaCard({data,refresh:async()=>{},draftPending});}};}
test('publication confirmation binds exact revision/fingerprints; stale review denied',async()=>{const h=await cardHarness();assert.equal(button(h.render(true),'Publish Auction').props.disabled,true);button(h.render(),'Publish Auction').props.onClick();assert.match(text(h.render()),/Configuration revision 2 · Auction revision 3 · Publication revision 4/);const requests=[];const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{requests.push(JSON.parse(o.body));return{ok:true,json:async()=>({ok:true})}};try{await button(h.render(),'Confirm Publish Auction').props.onClick();assert.equal(requests[0].action,'publish');assert.equal(requests[0].expectedAuctionRevision,3);assert.equal(requests[0].expectedAuctionFingerprint,'b'.repeat(64));button(h.render(),'Publish Auction').props.onClick();h.data.publications.calcutta.auctionRevision=4;assert.equal(button(h.render(),'Confirm Publish Auction').props.disabled,true);await button(h.render(),'Confirm Publish Auction').props.onClick();assert.equal(requests.length,1);}finally{globalThis.fetch=old;}});
test('saved summary, payment warning, no participant/financial authority changes',async()=>{const h=await editorHarness();h.cells[0]=fx;h.cells[1]=model.configurationDraft(fx);button(h.render(),'Review Auction').props.onClick();const lists=elements(h.render()).filter(e=>e.props?.rows);assert.equal(lists[0].props.rows.length,24);assert.equal(lists[0].props.onEdit,undefined);assert.match(text(h.render()),/Partial roster auctions are supported/);assert.match(text(h.exports.FinancialSafety()),/No money is collected or transferred/);const source=await readFile(new URL('../app/admin/director/ProductionDirectorOperations.js',import.meta.url),'utf8');assert.match(source,/Unpublishing hides participant visibility; it does not delete facts or remove financial dependencies/);});

test('Clear scope remains limited to Calcutta; other Director and participant files unchanged from Release 132',async()=>{const {execFileSync}=await import('node:child_process');const root=new URL('../',import.meta.url);const paths=execFileSync('git',['diff','4f880f04e19b13f97cab5cd1b0c5a20213f55d53','--name-only'],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(Boolean);const allowed=new Set(['app/admin/director/CalcuttaManagementEditor.js','app/admin/director/calcutta-management.module.css','app/api/admin/production-calcutta-v1/route.js','lib/calcutta-management-server.js','lib/production-calcutta-server.js','supabase/production_incremental/director-calcutta-clear-entry-v1.sql']);for(const p of paths)assert.ok(p.startsWith('test/')||allowed.has(p),p);const before=execFileSync('git',['show','4f880f04e19b13f97cab5cd1b0c5a20213f55d53:app/admin/director/ProductionDirectorOperations.js'],{cwd:root,encoding:'utf8'});const after=await readFile(new URL('../app/admin/director/ProductionDirectorOperations.js',import.meta.url),'utf8');for(const [a,b] of [['export function TournamentDayPanel','function decimalMoney'],['export function DraftGuidePanel','const AUDIT_FILTERS']]){assert.equal(after.slice(after.indexOf(a),after.indexOf(b)),before.slice(before.indexOf(a),before.indexOf(b)));}});

test('fingerprint-only changes invalidate publication review; published/uncertain editor remains locked',async()=>{const h=await cardHarness();button(h.render(),'Publish Auction').props.onClick();h.data.publications.calcutta.auctionFingerprint='c'.repeat(64);assert.equal(button(h.render(),'Confirm Publish Auction').props.disabled,true);const e=await editorHarness();e.cells[0]={...fx,publication_state:'PUBLISHED'};e.cells[1]=model.configurationDraft(fx);assert.equal(list(e.render()).props.disabled,true);});
test('Unpublish sends only the existing revision contract and preserves local financial projection',async()=>{const h=await cardHarness();h.data.publications.calcutta.published=true;h.data.publications.calcutta.publicationState='PUBLISHED';h.data.privateOperations.calcutta.publicationState='PUBLISHED';const facts=JSON.stringify(h.data.privateOperations.calcutta.auction);const oldFetch=globalThis.fetch,oldConfirm=globalThis.confirm;let sent;globalThis.confirm=()=>true;globalThis.fetch=async(u,o)=>{sent=JSON.parse(o.body);return{ok:true,json:async()=>({ok:true})}};try{await button(h.render(),'Unpublish').props.onClick();assert.equal(sent.action,'unpublish');assert.equal(sent.expectedAuctionRevision,3);assert.equal(sent.expectedAuctionFingerprint,'b'.repeat(64));assert.equal(sent.purchases,undefined);assert.equal(sent.ownership,undefined);assert.equal(JSON.stringify(h.data.privateOperations.calcutta.auction),facts);assert.match(text(h.render()),/without deleting auction facts/);}finally{globalThis.fetch=oldFetch;globalThis.confirm=oldConfirm;}});
