import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile}from'node:fs/promises';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';
import{createIsolatedCluster,createDatabase,destroyIsolatedCluster,sql,sqlFile,jsonLiteral,repositoryRoot}from'./support/reliability/postgres17.mjs';
import{installLocalCanonicalPlatform}from'./support/reliability/phase2d-resource-bootstrap.mjs';import{enableOwnedSafeupdate}from'./support/reliability/pg-safeupdate.mjs';
import{readModelDImage}from'../tools/reliability/model-d-bootstrap.mjs';import{createModelDFixture}from'./support/reliability/certification-model-d-fixture.mjs';
import{renderModelDBinding,renderModelDRegistration}from'../tools/reliability/certification-model-d-binding.mjs';
import{renderModelDFixture,modelDIdentities,modelDFixtureContract}from'../tools/reliability/certification-model-d-fixture.mjs';
import{renderModelDSessionLineageAttestation,renderModelDLineageVerification,originalModelDReceipt,currentStateVerificationSql,renderModelDLineageInstallation}from'../tools/reliability/certification-forward-lineage.mjs';
import registration from'../config/certification-model-d-registration.json'with{type:'json'};import{certificationSha256,certificationManifestDigest}from'../lib/canonical-resource-registration.js';
const hash=v=>createHash('sha256').update(v).digest('hex');const evidence=[];
const root=repositoryRoot+'/docs/reliability/phase2d-forward-lineage/evidence';
const old=(name)=>execFileSync('git',['show','df8ade31d819d4858a196385dfee77a69743f644:supabase/model_d_bootstrap/'+name],{cwd:repositoryRoot,maxBuffer:32*1024*1024,encoding:'utf8'});
async function upgraded(){const cluster=await createIsolatedCluster(),database='lineage_owned';try{
 createDatabase(cluster,database);installLocalCanonicalPlatform(cluster,database);const q=t=>sql(cluster,database,t,{role:''});
 const oldManifest=old('manifest.json'),om=JSON.parse(oldManifest);assert.equal(hash(oldManifest),originalModelDReceipt.manifest_sha256);assert.equal(om.artifacts.schema,originalModelDReceipt.schema_sha256);
 q(`begin;${old('schema.sql')}${old('static-contracts.sql')}insert into production_control.canonical_bootstrap_installation_v1(contract_version,manifest_sha256,schema_sha256,static_data_sha256)values('bagger-canonical-bootstrap-v1','${originalModelDReceipt.manifest_sha256}','${originalModelDReceipt.schema_sha256}','${originalModelDReceipt.static_data_sha256}');commit;`);
 const image=await readModelDImage();const newer=structuredClone(registration);newer.registration.schema_digest=image.manifest.artifacts.schema;newer.registration.server_key_sha256=certificationSha256('owned-local-lineage-server');newer.registration.public_key_sha256=certificationSha256('owned-local-lineage-public');
 const deployment={vercel_team_id:newer.registration.vercel_team_id,vercel_project_id:newer.registration.vercel_project_id,git_branch:newer.registration.git_branch,deployment_class:'preview',release_commit:'2e3f3042e3d2b7e39f078ca7d10f6081a5d008b4',deployment_id:'dpl_HSWrf1i5QbfKwhjpYUPC3ynfZbZk',deployment_origin:'https://bagger-6zi10a9o5-sandbagger-invitational.vercel.app'};
 const binding={purpose:'PART2C_DRESS_REHEARSAL',resource:newer.registration,deployment,binding_id:'d1000000-0000-4000-8000-000000000002',authority_epoch_id:'9f2d5b83-5fe0-4c3b-8314-32ee29026482'};
 // Model the committed historical owner registration/binding protocol with its original image, before any forward DDL.
 const originalRegistration=structuredClone(newer);originalRegistration.registration.schema_digest=om.artifacts.schema;
 const historic=s=>s.replaceAll(image.manifest.artifacts.schema,om.artifacts.schema).replaceAll(image.manifestDigest,hash(oldManifest)).replaceAll(certificationManifestDigest(newer),certificationManifestDigest(originalRegistration));
 q(historic(await renderModelDRegistration({purpose:binding.purpose,resource:binding.resource},{registrationManifest:newer})));q(historic(await renderModelDBinding(binding,{registrationManifest:newer})));
 const manifest=structuredClone(newer);manifest.registration.schema_digest=om.artifacts.schema;
 q(`alter table auth.users add column role text default 'authenticated';insert into auth.users(id,email,email_confirmed_at,role)select(value->>'auth_user_id')::uuid,value->>'email',clock_timestamp(),'authenticated'from jsonb_array_elements(${jsonLiteral(modelDIdentities)})`);
 const gen=JSON.parse(q('select to_jsonb(g)from production_control.certification_ingress_generations_v1 g'));
 const input={contract:modelDFixtureContract,operation_id:'certification-model-d-initial-fixture',resource:manifest.registration,deployment,expected:{binding_id:binding.binding_id,authority_epoch_id:binding.authority_epoch_id,activation_revision:1,admission_revision:1,pointer_revision:1,generation_id:gen.generation_id,generation_revision:gen.revision}};
 const f={cluster,database,q,input,manifest};await enableOwnedSafeupdate(f);return f;
}catch(e){await destroyIsolatedCluster(cluster);throw e;}}
const runVerification=async f=>f.q('begin;'+await renderModelDLineageVerification(f.input,{registrationManifest:f.manifest})+'rollback;');
function denied(f,name,sqlText,pattern){assert.throws(()=>f.q(sqlText),pattern||/ERROR:/,name);evidence.push({case:name,denied:true});}
test('fresh current image: exact lineage, atomic D9, replay and zero receipt rewrite',async()=>{const f=await createModelDFixture({provision:false});try{
 const receipt=f.q('select to_jsonb(r)from production_control.canonical_bootstrap_installation_v1 r');const verify=await renderModelDLineageVerification(f.fixtureRequest,{registrationManifest:f.registrationManifest});f.q('begin;'+verify+'rollback;');
 denied(f,'fresh fixture atomic failure',f.fixtureSql.replace("insert into scoring_authority.match_holes", "raise exception 'LOCAL_ATOMIC_FAILURE';insert into scoring_authority.match_holes"),/LOCAL_ATOMIC_FAILURE/);assert.equal(f.q('select count(*)from scoring_authority.players'),'0');
 f.q(f.fixtureSql);f.q(f.fixtureSql);assert.equal(f.q('select count(*)from scoring_authority.matches'),'24');assert.equal(f.q('select count(*)from scoring_authority.match_holes'),'432');assert.equal(f.q('select count(*)from scoring_authority.hole_scores'),'0');assert.equal(f.q('select to_jsonb(r)from production_control.canonical_bootstrap_installation_v1 r'),receipt);
 denied(f,'fresh conflicting replay',f.fixtureSql.replace('"operation_id":"certification-model-d-initial-fixture"','"operation_id":"conflict"'));
 evidence.push({case:'fresh current image and fixture replay',pass:true});
}finally{await destroyIsolatedCluster(f.cluster);}});
test('actual predecessor + forward + retrospective attestation: security, immutability, drift and D9',async()=>{const f=await upgraded();try{
 const receipt=f.q('select to_jsonb(r)from production_control.canonical_bootstrap_installation_v1 r');const forward=repositoryRoot+'/supabase/production_incremental/certification-session-link-status-v1.sql';sqlFile(f.cluster,f.database,forward,{role:''});assert.equal(f.q("select to_regclass('production_control.certification_forward_lineage_v1')is null"),'t');
 const image=await readModelDImage();denied(f,'predecessor direct-current receipt rejection',`do $$begin if not(select to_jsonb(r)@>${jsonLiteral({manifest_sha256:image.manifestDigest,schema_sha256:image.manifest.artifacts.schema})} from production_control.canonical_bootstrap_installation_v1 r)then raise exception 'CERTIFICATION_FIXTURE_INSTALLATION_DENIED';end if;end$$;`,/CERTIFICATION_FIXTURE_INSTALLATION_DENIED/);
 const artifact=await readFile(repositoryRoot+'/supabase/production_incremental/certification-forward-lineage-attestation-v1.sql','utf8');
 denied(f,'forward mismatch rollback',artifact.replace('begin;',"begin;alter function production_control.certification_session_link_status_v1(jsonb)security invoker;"),/PREDECESSOR_MISMATCH/);assert.equal(f.q("select to_regclass('production_control.certification_forward_lineage_v1')is null"),'t');
 const installation=await renderModelDLineageInstallation(f.input,{registrationManifest:f.manifest});f.q(installation);f.q(installation);const verification=await renderModelDLineageVerification(f.input,{registrationManifest:f.manifest});denied(f,'missing attestation','begin;'+verification+'rollback;',/MISSING_OR_EXTRA/);
 const record=await renderModelDSessionLineageAttestation(f.input,{registrationManifest:f.manifest});const start=Date.now();f.q(record);const row=f.q('select to_jsonb(r)from production_control.certification_forward_lineage_v1 r');f.q(record);assert.equal(row,f.q('select to_jsonb(r)from production_control.certification_forward_lineage_v1 r'));assert.ok(Date.parse(JSON.parse(row).created_at)>=start-1000);assert.equal(JSON.parse(row).payload.execution_evidence.execution_time,null);assert.equal(f.q('select to_jsonb(r)from production_control.canonical_bootstrap_installation_v1 r'),receipt);await runVerification(f);
 for(const role of ['anon','authenticated','service_role']){denied(f,role+' private attestation read',`set role ${role};select * from production_control.certification_forward_lineage_v1`,/permission denied/);denied(f,role+' owner record',record.replace('begin;',`begin;set local role ${role};`),/OWNER_REQUIRED|permission denied/);}
 for(const statement of ['update production_control.certification_forward_lineage_v1 set revision=2 where true','delete from production_control.certification_forward_lineage_v1 where true','truncate production_control.certification_forward_lineage_v1','update production_control.canonical_bootstrap_installation_v1 set schema_sha256=repeat(\'0\',64) where true','delete from production_control.canonical_bootstrap_installation_v1 where true'])denied(f,'immutability '+statement.split(' ')[0],statement,/IMMUTABLE/);
 const mutations=[['missing function','drop function public.read_certification_session_link_status_v1(jsonb)'],['extra function',"create function public.unapproved_lineage_probe()returns int language sql as 'select 1'"],['PUBLIC grant','grant select on production_control.certification_session_keys_v1 to public'],['function drift',"alter function production_control.certification_session_link_status_v1(jsonb)security invoker"],['body drift',"create or replace function public.read_certification_session_link_status_v1(input jsonb)returns jsonb language plpgsql security definer set search_path=pg_catalog as $$begin return '{}'::jsonb;end$$"],['ACL drift','grant execute on function production_control.certification_session_link_status_v1(jsonb)to service_role'],['owner drift','alter function production_control.certification_session_link_status_v1(jsonb)owner to service_role'],['search path drift','alter function production_control.certification_session_link_status_v1(jsonb)set search_path=public'],['RLS drift','alter table production_control.certification_session_keys_v1 disable row level security'],['policy drift','create policy leaked on production_control.certification_session_keys_v1 using(true)'],['private exposure','grant select on production_control.certification_session_keys_v1 to authenticated'],['unexpected public relation','create table public.unexpected_lineage_probe(id int)'],['static drift',"delete from production_control.worker_engine_release_catalog_v1 where true"]];
 for(const [name,mutation]of mutations){if(name==='static drift')continue;denied(f,name,'begin;'+mutation+';'+verification+'rollback;',/MODEL_D_CATALOG_MISMATCH/);}
 const staticTable=/INSERT INTO ([\w.]+)/.exec(image.staticData)[1];denied(f,'static data drift',`begin;alter table ${staticTable} disable trigger user;delete from ${staticTable} where true;alter table ${staticTable} enable trigger user;${verification}rollback;`,/STATIC_MISMATCH/);
 for(const [section,k,v]of [['resource','resource_id','CERTIFICATION:2857f707-065a-405d-b5fc-b5b6fa1b0f51'],['resource','project_ref','trmcwrljjxwhgtikfdgu'],['resource','registration_revision',2],['deployment','deployment_id','dpl_WrongBinding'],['deployment','release_commit','f'.repeat(40)],['expected','admission_revision',2],['expected','authority_epoch_id','d1000000-0000-4000-8000-000000000099']]){const changed=structuredClone(f.input);changed[section][k]=v;try{const s=await renderModelDLineageVerification(changed,{registrationManifest:f.manifest});denied(f,'wrong binding '+section+'.'+k,'begin;'+s+'rollback;');}catch(e){assert.ok(e instanceof assert.AssertionError);evidence.push({case:'wrong binding '+section+'.'+k,denied:true});}}
 for(const token of ['artifact_sha256','current_static_sha256','current_catalog_artifact_sha256']){const payload=JSON.parse(row).payload;denied(f,'conflicting '+token,record.replace(payload[token], '0'.repeat(64)),/CONFLICT|STATIC|CATALOG/);}
 // Trusted-owner tampering model: bypassing the trigger is catalog drift and therefore never accepted.
 denied(f,'tampered attestation','begin;alter table production_control.certification_forward_lineage_v1 disable trigger certification_lineage_immutable_v1;update production_control.certification_forward_lineage_v1 set payload=\'{}\'::jsonb where true;'+verification+'rollback;',/MODEL_D_CATALOG_MISMATCH/);
 denied(f,'unknown extra lineage',"begin;insert into production_control.certification_forward_lineage_v1(attestation_id,resource_id,revision,payload,original_receipt)values('UNAPPROVED','unknown',2,'{}','{}');"+verification+'rollback;',/MISSING_OR_EXTRA/);

 for(const [name,change]of [
 ['missing original receipt','delete from production_control.canonical_bootstrap_installation_v1 where true'],
 ['wrong original receipt',"update production_control.canonical_bootstrap_installation_v1 set manifest_sha256=repeat('0',64) where true"],
 ['substituted current receipt',`update production_control.canonical_bootstrap_installation_v1 set manifest_sha256='${image.manifestDigest}',schema_sha256='${image.manifest.artifacts.schema}' where true`]
 ])denied(f,name,'begin;set local session_replication_role=replica;'+change+';set local session_replication_role=origin;'+verification+'rollback;',/MODEL_D_LINEAGE_/);
 const changedFields=[['resource_id','wrong-resource'],['project_ref','wrong-project'],['artifact_id','unapproved.sql'],['artifact_sha256','0'.repeat(64)],['execution_evidence.sha256','0'.repeat(64)],['predecessor.schema_sha256','0'.repeat(64)],['successor.catalog_artifact_sha256','0'.repeat(64)],['current_normalized_catalog_sha256','0'.repeat(64)],['current_static_sha256','0'.repeat(64)],['authority_epoch_id','wrong-epoch'],['resource_revision',2]];
 for(const [field,value]of changedFields){const path='{'+field.split('.').join(',')+'}';denied(f,'tampered '+field,`begin;alter table production_control.certification_forward_lineage_v1 disable trigger certification_lineage_immutable_v1;update production_control.certification_forward_lineage_v1 set payload=jsonb_set(payload,'${path}',${jsonLiteral(value)})where true;alter table production_control.certification_forward_lineage_v1 enable trigger certification_lineage_immutable_v1;${verification}rollback;`,/ATTESTATION_DENIED/);}
 for(const role of ['anon','authenticated','service_role'])denied(f,role+' direct insert',`set role ${role};insert into production_control.certification_forward_lineage_v1(attestation_id,resource_id,revision,payload,original_receipt)values('x','x',2,'{}','{}')`,/permission denied/);
 evidence.push({case:'current normalized contract',catalogDigest:JSON.parse(row).payload.current_normalized_catalog_sha256,artifactDigest:JSON.parse(row).payload.current_catalog_artifact_sha256,staticDigest:JSON.parse(row).payload.current_static_sha256});
 const fixture=await renderModelDFixture(f.input,{registrationManifest:f.manifest});denied(f,'upgraded fixture atomic rollback',fixture.replace('insert into scoring_authority.match_holes',"raise exception 'LOCAL_ATOMIC_FAILURE';insert into scoring_authority.match_holes"),/LOCAL_ATOMIC_FAILURE/);assert.equal(f.q('select count(*)from scoring_authority.players'),'0');f.q(fixture);f.q(fixture);assert.equal(f.q('select count(*)from scoring_authority.matches'),'24');assert.equal(f.q('select to_jsonb(r)from production_control.canonical_bootstrap_installation_v1 r'),receipt);
 evidence.push({case:'forward upgraded attested fixture and replay',pass:true,receiptUnchanged:true,retrospective:true});
}finally{await destroyIsolatedCluster(f.cluster);await writeFile(root+'/focused.json',JSON.stringify(evidence,null,2)+'\n');}});
