// Bounded exact-eligibility model only. Not the chronological dress rehearsal.
// All source facts below use real Director/scoring operations, never job/result inserts.
import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{writeFile,mkdir}from'node:fs/promises';
import{createModelDFixture}from'./support/reliability/certification-model-d-fixture.mjs';
import{destroyIsolatedCluster,repositoryRoot,jsonLiteral,sqlResult}from'./support/reliability/postgres17.mjs';
import{certificationDirectorStack}from'./support/reliability/certification-director-proof.mjs';
import{certificationOddsStack}from'./support/reliability/certification-odds-proof.mjs';
import{certificationProjectionRpc,certificationOperationRpc}from'../lib/certification-runtime-server.js';
import{canonicalDirectorOperationsRequest}from'../lib/canonical-director-operations-client.js';
import{consumeCertificationQueueMessage,QUEUE_TOPIC}from'../lib/certification-queue-supervision.js';
import {QueueClient}from'@vercel/queue';
import{handleQueueEnvelope,requireQueueEnvelopeMetadata}from'../lib/certification-queue-envelope.js';
import{queueRetry}from'../lib/certification-queue-supervision.js';
import{QUEUE_TIMING}from'../lib/certification-queue-timing.js';
const output=repositoryRoot+'/docs/reliability/phase2d-model-d/evidence';
const key=()=>randomUUID();
test('Model D exact Final Results Odds eligibility and native Queue FinalRecap admission',async t=>{
 const f=await createModelDFixture(),e={hosted:false,fullChronologyClaimed:false,manualJobInserts:0,manualResultInserts:0,cases:[]};
 const run=async(name,fn)=>{let err;await t.test(name,async()=>{try{await fn();e.cases.push({name,result:'PASS'});}catch(x){err=x;throw x;}});if(err)throw err;};
 const invoke=(op,payload,auth=f.authorization,id=key())=>certificationOperationRpc(op,payload,{env:f.env,authorization:auth,operationRequestId:id},f.dependencies);
 const ready=()=>f.q("select production_control.derived_final_recap_ready_v1('2026')");
 const jobs=()=>JSON.parse(f.q("select coalesce(jsonb_agg(to_jsonb(j)order by engine_key),'[]')from scoring_authority.competition_recalculation_jobs j"));
 const match=id=>JSON.parse(f.q(`select to_jsonb(m)from scoring_authority.matches m where match_id='${id}'`));
 const completedWrites=[];const originalFetch=f.dependencies.fetchImpl;f.dependencies.fetchImpl=async(url,init)=>{const r=await originalFetch(url,init);const input=JSON.parse(init.body).input;
 if(input.operation_id==='WORKERS.INTELLIGENCE_WRITE'&&r.ok)completedWrites.push(input);return r;};
 let director,odds,calculation,publication;
 const native=async(entry)=>{const now=Date.now(),before=globalThis.fetch,calls=[];let value;
 const fetchImpl=async(url,init)=>{assert.equal(new URL(url).origin,'https://iad1.vercel-queue.com');assert.equal(new Headers(init.headers).get('Vqs-Deployment-Id'),f.deployment.deployment_id);calls.push(init.method);return init.method==='DELETE'?new Response(null,{status:204}):Response.json({success:true});};
 const client=new QueueClient({region:'iad1',deploymentId:f.deployment.deployment_id,token:'synthetic-local-only',telemetry:{isEnabled:false}});
 const callback=client.handleCallback(async(message,meta)=>{requireQueueEnvelopeMetadata(meta,message);value=await consumeCertificationQueueMessage(message,meta,{env:f.env,dependencies:f.dependencies});},{visibilityTimeoutSeconds:90,retry:queueRetry});
 const request=new Request(f.deployment.deployment_origin+'/api/internal/derived-worker/queue',{method:'POST',headers:{'content-type':'application/json','ce-type':'com.vercel.queue.v2beta','ce-vqsqueuename':QUEUE_TOPIC,'ce-vqsconsumergroup':'synthetic','ce-vqsmessageid':'msg_local_'+entry.message.invocation_id,'ce-vqsregion':'iad1','ce-vqsreceipthandle':'synthetic_receipt','ce-vqsdeliverycount':'1','ce-vqscreatedat':new Date(now-1000).toISOString(),'ce-vqsexpiresat':new Date(now+540000).toISOString()},body:JSON.stringify(entry.message)});
 try{globalThis.fetch=fetchImpl;const response=await handleQueueEnvelope(request,callback,{bound:f.bound,control:f.control(),getToken:async()=> 'synthetic-local-only',fetchImpl});assert.equal(response.status,200);return {value,closure:await response.json(),calls};}finally{globalThis.fetch=before;}};
 const deliver=async(startOptions={})=>{f.start(startOptions);const entries=f.batch().messages;assert.equal(entries.length,1);const entry=entries[0];f.register(entry);const wait=Date.parse(entry.scheduled_at)-Date.now()+100;if(wait>0)await new Promise(r=>setTimeout(r,wait));const started=performance.now(),result=await native(entry);const elapsed=performance.now()-started;if(f.status().state==='ENABLED')f.stop();return{entry,result:result.value,elapsed,transport:result.calls};};
 try{
 f.toggle(true);director=await certificationDirectorStack(f);
 await run('fresh fixture FinalRecap ineligible and no attempt, calculation or publication',()=>{assert.equal(ready(),'f');assert.equal(f.q("select count(*)from scoring_authority.competition_derived_snapshots where engine_key='TOURNAMENT_FINAL_RECAP'and is_current"),'0');});
 await run('Director configures fixed synthetic Odds inputs through actual route',async()=>{const c=await canonicalDirectorOperationsRequest(null,{family:'ODDS_INPUT_CONFIGURATION',fetchImpl:director.request});const r=await canonicalDirectorOperationsRequest({family:'ODDS_INPUT_CONFIGURATION',action:'configure',operationRequestId:key(),expectedContextToken:c.context.contextToken,payload:{expectedConfigurationRevision:0,profile:'CERTIFICATION_DEFAULTS_V1',confirmation:'CONFIGURE SYNTHETIC ODDS INPUTS',reason:'Owned local Model D exact eligibility model; no Google or Production.'}},{family:'ODDS_INPUT_CONFIGURATION',fetchImpl:director.request});assert.equal(r.receipt.ok,true);});
 await run('bounded exact-eligibility source model: all 24 complete FINAL via canonical Director/scoring',async()=>{
 const matches=JSON.parse(f.q("select jsonb_agg(match_id order by round_number,match_id)from scoring_authority.matches"));
 for(const id of matches){await f.mutation('prepare-scoring-context',{matchId:id});
 for(const action of['mark-live']){const m=match(id);await director.transport.controlRequest(action,{matchId:id,expectedMatchRevision:m.match_revision,expectedPermissionRevision:m.permission_revision,operationRequestId:key()}).catch(error=>{error.message+=' '+JSON.stringify(director.calls.findLast(c=>c.error)?.error);throw error;});}
 for(let h=1;h<=18;h++){const m=match(id),n=m.format==='BB'?2:1,idKey=key();const result=await invoke('SCORING.SUBMIT_HOLE',{match_id:id,mutation_key:idKey,hole_number:h,expected_match_revision:m.match_revision,expected_hole_revision:0,team_1_gross_scores:Array(n).fill(4),team_2_gross_scores:Array(n).fill(5)},{...f.authorization,match_id:id,permission_revision:m.permission_revision},idKey);assert.equal(result.payload.ok,true,JSON.stringify(result.payload));}
 const m=match(id),idKey=key();const result=await invoke('SCORING.FINALIZE_MATCH',{match_id:id,mutation_key:idKey,expected_match_revision:m.match_revision},{...f.authorization,match_id:id,permission_revision:m.permission_revision},idKey);assert.equal(result.payload.ok,true,JSON.stringify(result.payload));}
 assert.equal(f.q("select count(*)from scoring_authority.matches where status='FINAL'and scorecard_complete"),'24');assert.equal(f.q('select count(*)from scoring_authority.hole_scores'),'432');assert.equal(ready(),'f');e.sourceModel={matches:24,complete:24,final:24,canonicalHoleCommits:432,purpose:'Exact eligibility admission only; no milestone chronology rehearsal'};});
 await run('normal private Queue drains exact-source modeling backlog while FinalRecap remains ineligible',async()=>{e.backlog=[];for(let n=0;n<120;n++){const counts=f.status().counts;e.backlog.push(counts);if(counts.pending_work===0&&counts.pending_intents===0)break;await deliver();if(n%5===0)console.log('Model D local drain',n,counts);}const c=f.status().counts;assert.equal(c.pending_work,0,JSON.stringify(c));assert.equal(c.pending_intents,0,JSON.stringify(c));assert.equal(ready(),'f');assert.equal(f.q("select count(*)from scoring_authority.competition_derived_snapshots where engine_key='TOURNAMENT_FINAL_RECAP'"),'0');});
 await run('Final Results Odds uses existing bound Preview after() checkpointed processor; no Queue engine',async()=>{odds=await certificationOddsStack(f);const c=await odds.client();calculation=await odds.client({action:'calculate',operationRequestId:key(),expectedContextToken:c.context.token,phase:'Final Results',iterations:10000});assert.equal(calculation.accepted,true);assert.equal(odds.scheduled.length,1);const start=performance.now();await odds.scheduled.shift()();e.oddsElapsedMs=performance.now()-start;const j=JSON.parse(f.q(`select to_jsonb(j)from scoring_authority.odds_calculation_jobs j where job_id='${calculation.jobId}'`));assert.equal(j.status,'SUCCEEDED');assert.equal(j.result_payload.phase,'Final Results');assert.ok(j.checkpoint_count>0);assert.equal(ready(),'f');e.odds={phase:j.phase,checkpoints:j.checkpoint_count,attempts:j.attempt_count};});
 await run('separate Director Final Results publication is final eligibility predicate',async()=>{const c=await odds.client(null,{jobId:calculation.jobId});const command={action:'publish',operationRequestId:key(),expectedContextToken:c.context.token,jobId:calculation.jobId,confirmPublication:true,expectedPublicationRevision:c.publication.revision,expectedSnapshotId:c.publication.snapshotId};publication=await odds.client(command);assert.equal(publication.publicationCreated,true);assert.equal((await odds.client(command)).duplicate,true);assert.equal(ready(),'t');});

 await run('real FinalRecap claim is superseded by lawful source advance; old completion denied',async()=>{
 const base=f.dependencies.fetchImpl;let used=false,oldOutcome;
 f.dependencies.fetchImpl=async(url,init)=>{const i=JSON.parse(init.body).input;
  if(i.operation_id==='WORKERS.INTELLIGENCE_WRITE'&&!used){used=true;assert.equal(jobs().find(j=>j.engine_key==='TOURNAMENT_FINAL_RECAP').status,'RUNNING');
   const m=match('2026-R3-12'),id=key();const reopened=await invoke('SCORING.REOPEN_MATCH',{match_id:m.match_id,mutation_key:id,expected_match_revision:m.match_revision},{...f.authorization,match_id:m.match_id,permission_revision:m.permission_revision},id);assert.equal(reopened.payload.ok,true,JSON.stringify(reopened.payload));assert.equal(ready(),'f');
   const response=await base(url,init);oldOutcome=await response.clone().json();assert.equal(oldOutcome.ok,false);assert.match(oldOutcome.code,/STALE/);return response;
  }return base(url,init);};
 try{await deliver();assert.ok(used);assert.equal(f.q("select count(*)from scoring_authority.competition_derived_snapshots where engine_key='TOURNAMENT_FINAL_RECAP'"),'0');}finally{f.dependencies.fetchImpl=base;}
 const m=match('2026-R3-12'),id=key();const finalized=await invoke('SCORING.FINALIZE_MATCH',{match_id:m.match_id,mutation_key:id,expected_match_revision:m.match_revision},{...f.authorization,match_id:m.match_id,permission_revision:m.permission_revision},id);assert.equal(finalized.payload.ok,true,JSON.stringify(finalized.payload));
 const c=await odds.client();calculation=await odds.client({action:'calculate',operationRequestId:key(),expectedContextToken:c.context.token,phase:'Final Results',iterations:10000});await odds.scheduled.shift()();
 const reviewed=await odds.client(null,{jobId:calculation.jobId});publication=await odds.client({action:'publish',operationRequestId:key(),expectedContextToken:reviewed.context.token,jobId:calculation.jobId,confirmPublication:true,expectedPublicationRevision:reviewed.publication.revision,expectedSnapshotId:reviewed.publication.snapshotId});assert.equal(ready(),'t');
 e.staleSource={activeRealClaim:true,oldCompletion:oldOutcome.code,sourceAdvance:'Canonical reopen/refinalize; scores unchanged',newVerifiedFinalOdds:publication.snapshotId};
 });
 await run('FinalRecap common transient backoff, preserved attempts and terminal dead-letter',async()=>{const base=f.dependencies.fetchImpl;let fault='40001';
 f.dependencies.fetchImpl=async(url,init)=>{const i=JSON.parse(init.body).input;if(i.operation_id==='WORKERS.INTELLIGENCE_WRITE'&&fault){const code=fault;fault=null;return Response.json({code,message:'SYNTHETIC_MODEL_D_COMPATIBILITY_FAILURE'},{status:400});}return base(url,init);};
 try{const transient=await deliver(f.status().state==='HALTED'?{action:'RESUME',reconciliation_reason:'Canonical stale claim denied; complete source restored with current verified Final Results Odds'}:{});const first=jobs().find(j=>j.engine_key==='TOURNAMENT_FINAL_RECAP');assert.equal(first.status,'PENDING');assert.equal(first.delivery_attempts,1);assert.equal(first.delivery_dead_letter_at,null);assert.ok(Date.parse(first.delivery_available_at)>Date.parse(first.started_at));e.transient={attempt:first.delivery_attempts,availableAt:first.delivery_available_at,outcome:transient.result.outcome};
 await new Promise(r=>setTimeout(r,Math.max(0,Date.parse(first.delivery_available_at)-Date.now()+100)));fault='23514';const terminal=await deliver();const dead=jobs().find(j=>j.engine_key==='TOURNAMENT_FINAL_RECAP');assert.equal(dead.status,'FAILED');assert.equal(dead.delivery_attempts,2);assert.ok(dead.delivery_dead_letter_at);assert.equal(f.status().state,'HALTED');const before=jobs();const closed=await native(terminal.entry);assert.equal(closed.value,undefined);assert.deepEqual(jobs(),before);e.terminal={attempt:dead.delivery_attempts,cycle:dead.delivery_cycle,outcome:terminal.result.outcome,haltedClosure:closed.closure};
 for(const j of jobs().filter(j=>j.delivery_dead_letter_at)){const id=key();const recovered=await invoke('DIRECTOR.REQUEUE_DERIVED',{contract_version:'score-derived-delivery-v1',tournament_id:'2026',family:'INTELLIGENCE',work_identity:'2026:0:'+j.engine_key,request_id:id,expected_cycle:j.delivery_cycle,expected_attempt:j.delivery_attempts,reason:'Owned local fixed cause corrected'},f.authorization,id);assert.equal(recovered.payload.ok,true);}
 assert.equal(jobs().find(j=>j.engine_key==='TOURNAMENT_FINAL_RECAP').delivery_attempts,0);assert.ok(Number(f.q("select count(*)from production_control.score_derived_delivery_attempts_v1 where work_identity='2026:0:TOURNAMENT_FINAL_RECAP'and transition='DEAD_LETTER'"))>0);
 }finally{f.dependencies.fetchImpl=base;}});
 await run('private Queue reservation executes existing Intelligence FinalRecap processor and publishes current result',async()=>{const delivery=await deliver({action:'RESUME',reconciliation_reason:'Owned local fixed cause corrected; truthful terminal history retained'});e.delivery=delivery.result;e.workerElapsedMs=delivery.elapsed;assert.equal(delivery.result.outcome,'SUCCEEDED',JSON.stringify(delivery.result));assert.ok(delivery.elapsed<45000);const recap=jobs().find(j=>j.engine_key==='TOURNAMENT_FINAL_RECAP');assert.equal(recap.status,'SUCCEEDED',JSON.stringify(recap));assert.equal(recap.delivery_attempts,1);assert.equal(f.q("select count(*)from scoring_authority.competition_derived_snapshots where engine_key='TOURNAMENT_FINAL_RECAP'and is_current"),'1');const repeat=await f.consume(delivery.entry);assert.equal(repeat.admitted,false);assert.equal(jobs().find(j=>j.engine_key==='TOURNAMENT_FINAL_RECAP').delivery_attempts,1);e.recap={cycle:recap.delivery_cycle,attempts:recap.delivery_attempts,source:recap.requested_source_revision,duplicate:repeat};});
 await run('completed old claim cannot write twice',()=>{const write=completedWrites.find(w=>w.payload.engines?.some(x=>x.key==='TOURNAMENT_FINAL_RECAP'));assert.ok(write);const repeated=f.rpc('execute_certification_operation_v1',write);assert.equal(repeated.ok,false);assert.match(repeated.code,/STALE/);assert.equal(f.q("select count(*)from scoring_authority.competition_derived_snapshots where engine_key='TOURNAMENT_FINAL_RECAP'and is_current"),'1');e.staleCompletion=repeated.code;});

 await run('participant-safe FinalRecap projection contains current result without claims or receipts',async()=>{const read=await certificationProjectionRpc('READS.CURRENT_VIEW',{surface:'COMPETITION_DERIVED',target_tournament_id:'2026',engine_keys:['TOURNAMENT_FINAL_RECAP']},{env:f.env},f.dependencies);assert.equal(read.payload.ok,true);const row=read.payload.data.snapshots.find(v=>v.engine_key==='TOURNAMENT_FINAL_RECAP');assert.ok(row);assert.equal(row.result_state,'OFFICIAL');assert.ok(row.result_payload);assert.doesNotMatch(JSON.stringify(read.payload),/claim_token|receipt_payload|supervisor_epoch/);e.read={engine:row.engine_key,state:row.result_state,participantSafe:true};});
 await run('STOP closes retained message without another worker/claim; wrong binding denied',async()=>{f.start();const entry=f.batch().messages[0];f.register(entry);f.stop();const stopped=await native(entry);assert.equal(stopped.value,undefined);assert.equal(stopped.closure.reason,'STOPPED');assert.equal(stopped.closure.transport_acknowledged,true);const oldCounts=jobs();for(const changes of[{project_ref:'trmcwrljjxwhgtikfdgu'},{resource_id:'CERTIFICATION:2857f707-065a-405d-b5fc-b5b6fa1b0f51'},{resource_class:'PRODUCTION'}]){const r=sqlResult(f.cluster,f.database,`set role service_role;select public.execute_certification_queue_supervisor_v2(${jsonLiteral({contract:'certification-queue-supervision-v2',...f.bound,resource:{...f.resource,...changes},operation:'BEGIN',invocation_id:entry.message.invocation_id})})`,{role:'service_role'});assert.notEqual(r.status,0);}assert.deepEqual(jobs(),oldCounts);e.stop=stopped;});
 await run('complete drain, OFF, disabled, paused and one current FinalRecap',()=>{const s=f.status();assert.equal(s.state,'OFF');assert.equal(s.counts.pending_work,0,JSON.stringify(s.counts));assert.equal(s.counts.pending_intents,0,JSON.stringify(s.counts));assert.equal(s.counts.active_claims,0);assert.equal(s.counts.active_leases,0);assert.equal(s.counts.dead_letters,0);assert.equal(s.reserved,0);f.toggle(false);assert.equal(f.q('select enabled from production_control.certification_admission_v1'),'f');assert.equal(f.q('select state from scoring_authority.ingress_gates'),'PAUSED');e.drain=s.counts;});
 }finally{await destroyIsolatedCluster(f.cluster);await mkdir(output,{recursive:true});await writeFile(output+'/focused-execution.json',JSON.stringify(e,null,2)+'\n');}
});
