// Certified manifest schema, exact starting gates and authority negatives; local files only.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateManifest,manifestDigest,canonical,assertStartingCheckpoint,assertPlannedScore,assertPhase,startingDigestSql,normalizedExpected} from '../tools/reliability/model-d-d10-manifest.mjs';
const fixture=JSON.parse(fs.readFileSync(new URL('../config/certification-model-d-fixture.json',import.meta.url)));
const path=new URL('../config/certification-model-d-d10-execution.json',import.meta.url);
const read=()=>JSON.parse(fs.readFileSync(path));
const actual=m=>({...m.startingCheckpoint,candidateSha:'f'.repeat(40),releaseSha:'f'.repeat(40),deploymentId:'dpl_OwnerReviewedReplacement',origin:'https://owner-reviewed.example',manifestDigest:manifestDigest(m),currentCanonicalBinding:true,providerVerifiedDirector:true,providerIdentity:'DIRECTOR_P01',role:'DIRECTOR',directorEntitlementCurrent:true,scoringContractInstalled:true,sourceHashes:m.implementation.sourceHashes});
const approved={manifestDigest:fs.existsSync(path)?manifestDigest(read()):null,candidateSha:'f'.repeat(40),deploymentId:'dpl_OwnerReviewedReplacement',origin:'https://owner-reviewed.example'};
test('committed complete manifest schema, canonical digest and replay',()=>{const m=read();assert.equal(validateManifest(m,fixture),true);assert.equal(fs.readFileSync(path,'utf8'),canonical(m));assert.equal(manifestDigest(m),fs.readFileSync(new URL('../config/certification-model-d-d10-execution.sha256',import.meta.url),'utf8').trim());assert.equal(manifestDigest(JSON.parse(canonical(m))),manifestDigest(m));assert.equal(new Set(m.matches.flatMap(x=>x.operations.map(o=>o.operationId))).size,432);});
test('exact reviewed D9/source/binding gate confers no authority',()=>{const m=read();assert.equal(assertStartingCheckpoint(m,actual(m),approved),true);for(const key of ['resource','project','profile','authorityEpoch','resourceRevision','branch','deploymentId','origin','releaseSha','candidateSha','providerIdentity','role']){const a=structuredClone(actual(m));a[key]='WRONG';assert.throws(()=>assertStartingCheckpoint(m,a,approved),key);}for(const key of Object.keys(m.startingCheckpoint.digests)){const a=structuredClone(actual(m));a.digests[key]='0'.repeat(64);assert.throws(()=>assertStartingCheckpoint(m,a,approved),key);}for(const key of ['currentCanonicalBinding','providerVerifiedDirector','directorEntitlementCurrent','scoringContractInstalled']){const a=structuredClone(actual(m));a[key]=false;assert.throws(()=>assertStartingCheckpoint(m,a,approved),key);}const a=structuredClone(actual(m));a.state.scores=1;assert.throws(()=>assertStartingCheckpoint(m,a,approved));a.state.scores=0;a.sourceHashes={};assert.throws(()=>assertStartingCheckpoint(m,a,approved));assert.throws(()=>assertStartingCheckpoint(m,actual(m),{...approved,manifestDigest:'0'.repeat(64)}));assert.equal(m.authority.granted,false);});
test('24/24 declared lawful actors, exact scoring facts, wrong actor/future state denied',()=>{const m=read();for(const match of m.matches){const phase={1:'D10.04',2:'D10.10',3:'D10.17'}[match.round];for(let hole=1;hole<=18;hole++)assert.equal(assertPlannedScore(m,{matchId:match.matchId,hole,actor:'DIRECTOR_P01',phase,lifecycleState:'LIVE_OPEN'}),match.operations[hole-1]);for(const change of [{actor:'PARTICIPANT_P12'},{phase:'D10.00'},{lifecycleState:'UPCOMING'},{hole:19},{matchId:'2026-R9-99'}])assert.throws(()=>assertPlannedScore(m,{matchId:match.matchId,hole:1,actor:'DIRECTOR_P01',phase,lifecycleState:'LIVE_OPEN',...change}));}assert.equal(m.authority.manualProcessor,'NOT_AUTHORIZED');assert.equal(m.authority.manualJobInsertion,'NOT_AUTHORIZED');});
test('phase guards deny future Odds/Recap, skipped chronology and shortcuts',()=>{const m=read();const a={previousPhase:'D10.06',resourceVerified:true,bindingVerified:true,finalRecapAttempts:0,finalResultsOddsPublished:false,finalMatchCount:6,manualProcessorInvocations:0,manualJobInsertions:0};assert.equal(assertPhase(m,'D10.07',a),true);for(const change of [{previousPhase:'D10.00'},{finalRecapAttempts:1},{finalResultsOddsPublished:true},{finalMatchCount:24},{manualProcessorInvocations:1},{manualJobInsertions:1},{bindingVerified:false}])assert.throws(()=>assertPhase(m,'D10.07',{...a,...change}));});
test('D9 digest readback is original C-order JSONB read-only algorithm',()=>{const sql=startingDigestSql();assert.match(sql,/BEGIN READ ONLY/);assert.match(sql,/collate "C"/);assert.match(sql,/CERTIFICATION_MODEL_D_FIXTURE_BOOTSTRAPPED/);assert.doesNotMatch(sql,/\b(?:INSERT|UPDATE|DELETE|CREATE|ALTER|TRUNCATE)\b/i);});
test('normalization excludes only declared publication wall clocks, never mathematics',()=>{const a={publishedAt:'a',probability:0.5},b={publishedAt:'b',probability:0.5};assert.deepEqual(normalizedExpected('ODDS',a),normalizedExpected('ODDS',b));b.probability=0.6;assert.notDeepEqual(normalizedExpected('ODDS',a),normalizedExpected('ODDS',b));assert.deepEqual(normalizedExpected('FINALRECAP',{story:'exact',opening:{publishedAt:'a',probability:0.5}}),normalizedExpected('FINALRECAP',{story:'exact',opening:{publishedAt:'b',probability:0.5}}));});
