import test from 'node:test';import assert from'node:assert/strict';import {readFile,mkdir,writeFile}from'node:fs/promises';
import {randomUUID}from'node:crypto';
import {createModelDFixture}from'./support/reliability/certification-model-d-fixture.mjs';
import {createIsolatedCluster,createDatabase,destroyIsolatedCluster,sql,sqlResult,jsonLiteral,sqlFile,repositoryRoot}from'./support/reliability/postgres17.mjs';
import {installLocalCanonicalPlatform}from'./support/reliability/phase2d-resource-bootstrap.mjs';
import {renderModelDInstallation}from'../tools/reliability/certification-model-d-installation.mjs';
import {installModelDImage,readModelDImage}from'../tools/reliability/model-d-bootstrap.mjs';
import {canonicalCatalog,assertCatalogConvergence,canonicalTableCounts}from'../tools/reliability/canonical-bootstrap-artifacts.mjs';
import {certificationResourceEnvironment}from'../lib/canonical-resource-registration.js';
import {supervisorEnvelope}from'../lib/certification-worker-supervision.js';
import {certificationProjectionRpc,certificationOperationRpc}from'../lib/certification-runtime-server.js';
import {modelDIdentities,validateModelDFixture}from'../tools/reliability/certification-model-d-fixture.mjs';
import {renderModelDBinding}from'../tools/reliability/certification-model-d-binding.mjs';
import {certificationDirectorStack}from'./support/reliability/certification-director-proof.mjs';
import {preflightQueueCallback}from'../lib/certification-queue-envelope.js';
import {createQueueTimingEvidence}from'../lib/certification-queue-timing-evidence.js';
import manifest from'../config/certification-model-d-fixture.json'with{type:'json'};
const output=repositoryRoot+'/docs/reliability/phase2d-model-d/evidence';
const literal=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const replaceRequest=(text,transform)=>{const match=/input jsonb:=('(?:''|[^'])*')::jsonb/.exec(text);assert.ok(match);const value=JSON.parse(match[1].slice(1,-1).replaceAll("''","'"));return text.replace(match[0],'input jsonb:='+literal(transform(value)));};
test('Model D fresh installation, exact resource and owner-only atomic full fixture',async t=>{
 const f=await createModelDFixture({provision:false}),e={hosted:false,pg17:true,safeupdate:'on',cases:[]};
 const run=async(name,fn)=>{let err;await t.test(name,async()=>{try{await fn();e.cases.push({name,result:'PASS'});}catch(x){err=x;throw x;}});if(err)throw err;};
 const state=()=>f.q("select jsonb_build_object('players',(select count(*)from scoring_authority.players),'matches',(select count(*)from scoring_authority.matches),'holes',(select count(*)from scoring_authority.match_holes),'audit',(select count(*)from production_control.operation_audit_events),'guide',(select count(*)from scoring_authority.guide_content_revisions))");
 try{
 await run('empty PG17 installation exact catalog ACL RLS owners search_paths dependencies and replay',async()=>{const b=await readModelDImage();assertCatalogConvergence(await canonicalCatalog(f.cluster,f.database),b.catalog);assert.match(f.q('select version()'),/PostgreSQL 17/);assert.equal(f.q("select current_setting('safeupdate.enabled')"),'on');await installModelDImage(f.cluster,f.database);});

 await run('rendered owner installation package verifies full catalog atomically and replays exactly',async()=>{createDatabase(f.cluster,'model_d_rendered');installLocalCanonicalPlatform(f.cluster,'model_d_rendered');const packageSql=await renderModelDInstallation({registrationManifest:f.registrationManifest});sql(f.cluster,'model_d_rendered',packageSql,{role:''});const b=await readModelDImage();assertCatalogConvergence(await canonicalCatalog(f.cluster,'model_d_rendered'),b.catalog);sql(f.cluster,'model_d_rendered',packageSql,{role:''});assertCatalogConvergence(await canonicalCatalog(f.cluster,'model_d_rendered'),b.catalog);await assert.rejects(renderModelDInstallation(),/placeholders disabled/);});
 await run('installation fault rolls back all schemas on empty target',async()=>{createDatabase(f.cluster,'model_d_rollback');installLocalCanonicalPlatform(f.cluster,'model_d_rollback');await assert.rejects(installModelDImage(f.cluster,'model_d_rollback',{failure:'after-static'}),/MODEL_D_INSTALL_INJECTED_FAILURE/);assert.equal(sql(f.cluster,'model_d_rollback',"select count(*)from pg_namespace where nspname in('production_control','scoring_authority','participant_identity')",{role:''}),'0');});
 await run('registration binding replay exact, conflicting replay rolls back and placeholders disabled',async()=>{assert.deepEqual(f.registrationStage,{registrations:1,epochs:0,pointers:0,admissionEnabled:0});const before=state();f.q(f.registrationSql);f.q(f.bindingSql);assert.equal(state(),before);assert.throws(()=>f.q(replaceRequest(f.bindingSql,v=>({...v,binding_id:randomUUID()}))),/MODEL_D_BINDING_CONFLICT/);await assert.rejects(renderModelDBinding(f.binding),/placeholders disabled/);});
 await run('owner package denied to all client roles including service_role and Director-shaped JWT',()=>{const before=state();for(const role of['anon','authenticated','service_role']){const r=sqlResult(f.cluster,f.database,`set role ${role};${f.fixtureSql}`,{role});assert.notEqual(r.status,0);assert.match(r.stderr,/OWNER_REQUIRED|permission denied/);}assert.throws(()=>f.q("set request.jwt.claim.role='authenticated';"+f.fixtureSql),/OWNER_REQUIRED/);assert.equal(state(),before);});
 const changes={missingPlayer:v=>{v.fixture.players.pop();},duplicatePlayer:v=>{v.fixture.players[23]=v.fixture.players[0];},wrongTeam:v=>{v.fixture.players[0].team_id='T2';},missingRound:v=>{v.fixture.rounds.pop();},wrongMatchCount:v=>{v.fixture.matches.pop();},wrongFormat:v=>{v.fixture.matches[0].format='SI';},duplicateMatch:v=>{v.fixture.matches[1]=v.fixture.matches[0];},wrongHoles:v=>{v.fixture.matches[0].holes.pop();},wrongRoundRelationship:v=>{v.fixture.matches[0].round=3;},wrongResource:v=>{v.resource.resource_id='CERTIFICATION:2857f707-065a-405d-b5fc-b5b6fa1b0f51';},wrongProject:v=>{v.resource.project_ref='trmcwrljjxwhgtikfdgu';},wrongRelease:v=>{v.deployment.release_commit='e'.repeat(40);},wrongDeployment:v=>{v.deployment.deployment_id='dpl_WrongModelDDeployment';},production:v=>{v.resource.resource_class='PRODUCTION';},oldPreview:v=>{v.resource.project_ref='idgigvjjqkfbqjeredpb';}};
 for(const [name,change]of Object.entries(changes))await run('denied fixed structure/binding '+name,()=>{const before=state();assert.throws(()=>f.q(replaceRequest(f.fixtureSql,v=>{change(v);return v;})),/MODEL_D_FIXED_MANIFEST_REQUIRED|CERTIFICATION_FIXTURE_/);assert.equal(state(),before);});
 for(const [name,setup]of Object.entries({admissionEnabled:"update production_control.certification_admission_v1 set enabled=true where resource_id='"+f.resource.resource_id+"';",ingressOpen:"update scoring_authority.ingress_gates set state='OPEN'where tournament_id='2026';",supervisorRunning:"update production_control.worker_supervisor_v1 set state='ENABLED'where singleton;"}))await run('denied unsafe checkpoint '+name,()=>{const before=state();const changed=f.fixtureSql.replace('begin;','begin;'+setup);assert.throws(()=>f.q(changed),/DISABLED_BOUND_CONTEXT|MODEL_D_SAFE_FIXTURE/);assert.equal(state(),before);});
 await run('failure after structural creation atomically rolls back every row and audit',()=>{const before=state();assert.throws(()=>f.q(f.fixtureSql.replace(' guide_validation:='," raise exception 'MODEL_D_FIXTURE_INJECTED_FAILURE';guide_validation:=")),/MODEL_D_FIXTURE_INJECTED_FAILURE/);assert.equal(state(),before);});
 await run('fixed fixture exact 24 2 3 24 6BB 6SC 12SI 432 zero scores results closed permissions',()=>{f.q(f.fixtureSql);e.structure=JSON.parse(f.q("select jsonb_build_object('players',(select count(*)from scoring_authority.players),'teams',(select count(*)from scoring_authority.teams),'rounds',(select count(*)from scoring_authority.rounds),'matches',(select count(*)from scoring_authority.matches),'BB',(select count(*)from scoring_authority.matches where format='BB'),'SC',(select count(*)from scoring_authority.matches where format='SC'),'SI',(select count(*)from scoring_authority.matches where format='SI'),'holes',(select count(*)from scoring_authority.match_holes),'scores',(select count(*)from scoring_authority.hole_scores),'final',(select count(*)from scoring_authority.matches where status='FINAL'),'open',(select count(*)from scoring_authority.scoring_permissions where can_score))"));assert.deepEqual(e.structure,{players:24,teams:2,rounds:3,matches:24,BB:6,SC:6,SI:12,holes:432,scores:0,final:0,open:0});assert.equal(f.q("select production_control.derived_final_recap_ready_v1('2026')"),'f');assert.equal(f.status().counts.pending_work,0);});
 await run('preexisting conflicting target is denied atomically before provisioning',()=>{const before=state();assert.throws(()=>f.q(f.fixtureSql.replace('begin;',"begin;insert into scoring_authority.players(player_id,display_name)values('P99','Synthetic conflicting target');")),/EMPTY_STRUCTURAL_TABLES|FIXTURE_DRIFT/);assert.equal(state(),before);});
 await run('fixture exact replay adds no structural or audit rows; conflicting replay and drift denied',()=>{const before=state();f.q(f.fixtureSql);assert.equal(state(),before);assert.throws(()=>f.q(replaceRequest(f.fixtureSql,v=>({...v,operation_id:'wrong'}))),/APPROVED_REQUEST_REQUIRED/);assert.throws(()=>f.q(f.fixtureSql.replace('begin;',"begin;update scoring_authority.players set display_name='Changed'where player_id='P24';")),/FIXTURE_DRIFT/);assert.equal(state(),before);});
 await run('server exact-resource isolation and no client selector',async()=>{assert.equal(certificationResourceEnvironment(f.env,f.dependencies).eligible,true);for(const changed of[{BAGGER_CERTIFICATION_RESOURCE_ID:'CERTIFICATION:2857f707-065a-405d-b5fc-b5b6fa1b0f51'},{SUPABASE_SCORING_MIRROR_URL:'https://trmcwrljjxwhgtikfdgu.supabase.co'},{VERCEL_DEPLOYMENT_ID:'dev'},{VERCEL_ENV:'production'},{PRODUCTION_ENABLED:'true'}])assert.throws(()=>supervisorEnvelope({...f.env,...changed},f.dependencies));await assert.rejects(certificationProjectionRpc('READS.CURRENT_VIEW',{surface:'TOURNAMENT',resource_id:'client-selected'},{env:f.env},f.dependencies),/authority|input|Certification/i);});
 await run('Model D native routing accepts only validated immutable server registration',async()=>{const id=randomUUID(),body={contract:'certification-queue-supervision-v2',invocation_id:id};const request=new Request('https://local-model-d-certification.vercel.app/api/internal/derived-worker/queue',{method:'POST',headers:{'ce-type':'com.vercel.queue.v2beta','ce-vqsqueuename':'bagger-certification-derived-wake-v2','ce-vqsconsumergroup':'model-d','ce-vqsmessageid':'msg_model_d'}});let calls=0;const options={bound:f.bound,getToken:async()=> 'synthetic-provider-identity',fetchImpl:async()=>{calls++;return Response.json({}, {status:404});}};assert.equal((await preflightQueueCallback(request,options)).status,200);assert.equal(calls,1);calls=0;await assert.rejects(preflightQueueCallback(request,{...options,bound:structuredClone(f.bound)}),/SUPERVISOR_DELIVERY_DENIED/);assert.equal(calls,0);assert.throws(()=>createQueueTimingEvidence({bound:structuredClone(f.bound)}));assert.ok(createQueueTimingEvidence({bound:f.bound,emit:()=>{}}));assert.equal(Object.isFrozen(f.bound.resource),true);});
 await run('shipping Tournament Guide Home participant context exact resource; private tables inaccessible',async()=>{f.toggle(true);for(const surface of['TOURNAMENT_LIVE','PARTICIPANT_HOME']){const r=await certificationProjectionRpc('READS.CURRENT_VIEW',{surface,...(surface==='PARTICIPANT_HOME'?{player_id:'P12'}:{})},{env:f.env},f.dependencies);assert.equal(r.payload.ok,true,JSON.stringify(r.payload));}const g=await certificationProjectionRpc('READS.GUIDE',{}, {env:f.env},f.dependencies);assert.equal(g.payload.ok,true);for(const id of modelDIdentities){const r=await certificationProjectionRpc('READS.IDENTITY_FOR_AUTH',{target_auth_user_id:id.auth_user_id},{env:f.env},f.dependencies);assert.equal(r.payload.ok,true,JSON.stringify(r.payload));}for(const role of['anon','authenticated','service_role'])assert.notEqual(sqlResult(f.cluster,f.database,`set role ${role};select * from production_control.certification_model_d_profile_v1`,{role}).status,0);});
 await run('initial participant score submission remains denied with every permission revoked',async()=>{const id=randomUUID();await assert.rejects(certificationOperationRpc('SCORING.SUBMIT_HOLE',{match_id:'2026-R1-6',mutation_key:id,hole_number:1,expected_match_revision:0,expected_hole_revision:0,team_1_gross_scores:[4,4],team_2_gross_scores:[5,5]},{env:f.env,operationRequestId:id,authorization:{role:'PLAYER',tournament_id:'2026',match_id:'2026-R1-6',player_id:'P12',auth_user_id:modelDIdentities[1].auth_user_id,permission_revision:1}},f.dependencies));assert.equal(f.q('select count(*)from scoring_authority.hole_scores'),'0');assert.equal(f.q('select count(*)from scoring_authority.scoring_permissions where can_score or revoked_at is null'),'0');});

 await run('closed Model D engine registry and all foreign runtime identities deny without work',()=>{f.toggle(true);for(const engines of [['CALCUTTA','ARBITRARY_SQL'],['TOURNAMENT_FINAL_RECAP'],[...f.status().engines,'NET_SKINS']])assert.throws(()=>f.start({engines}),/ENGINE|SCOPE|INVALID|SAFE_START_REQUIRED/);const before=state();for(const changes of [{resource:{...f.bound.resource,resource_id:'CERTIFICATION:2857f707-065a-405d-b5fc-b5b6fa1b0f51'}},{resource:{...f.bound.resource,project_ref:'trmcwrljjxwhgtikfdgu'}},{resource:{...f.bound.resource,project_ref:'idgigvjjqkfbqjeredpb'}},{resource:{...f.bound.resource,resource_class:'PRODUCTION'}},{deployment:{...f.bound.deployment,deployment_id:'dpl_ForeignModelDDeployment'}},{deployment:{...f.bound.deployment,release_commit:'e'.repeat(40)}}])assert.throws(()=>f.rpc('execute_certification_queue_supervisor_v2',{contract:'certification-queue-supervision-v2',...f.bound,...changes,operation:'BEGIN',invocation_id:randomUUID()}),/DENIED|STALE|MISMATCH/);assert.equal(state(),before);assert.equal(f.status().state,'OFF');assert.equal(f.status().counts.active_claims,0);});
 await run('normal Director setup all rounds and all matches; no scores or final state',async()=>{f.toggle(true);const s=await certificationDirectorStack(f);const model=await s.transport.setupRequest();assert.equal(model.data.matches.length,24);for(const round of manifest.rounds){await f.mutation('update-round',{roundNumber:round.round,format:round.format,roundName:'Synthetic Round '+round.round,teamSize:round.format==='SI'?1:2,pointsAvailable:round.format==='SI'?'3':'1',handicapAllowance:'1'});}for(const m of manifest.matches){const result=await f.mutation('prepare-scoring-context',{matchId:m.match_id});assert.equal(result.payload.ok,true,JSON.stringify(result.payload));}assert.equal(f.q('select count(*)from scoring_authority.hole_scores'),'0');f.toggle(false);e.director={rounds:3,matches:24,existingRequiredErrors:0};});
 }finally{await destroyIsolatedCluster(f.cluster);await mkdir(output,{recursive:true});await writeFile(output+'/focused-structure.json',JSON.stringify(e,null,2)+'\n');}
});

test('D7 empty-resource Queue acceptance and D8 STOP do not obstruct separately authorized D9 fixture',async()=>{const f=await createModelDFixture({provision:false,trustAcceptanceBeforeFixture:true});try{assert.equal(f.fixtureRequest.expected.admission_revision,3);assert.equal(f.status().state,'OFF');assert.equal(f.status().counts.pending_work,0);assert.equal(f.q('select count(*)from scoring_authority.hole_scores'),'0');assert.equal(f.q('select count(*)from scoring_authority.players'),'0');assert.equal(f.q('select enabled from production_control.certification_admission_v1'),'f');f.q(f.fixtureSql);assert.equal(f.q('select count(*)from scoring_authority.matches'),'24');assert.equal(f.q('select count(*)from scoring_authority.hole_scores'),'0');f.q(f.fixtureSql);}finally{await destroyIsolatedCluster(f.cluster);}});
