import assert from 'node:assert/strict';
import test from 'node:test';
import {createParticipantPhoneLoginHandler} from '../lib/participant-phone-login-handler.js';
import {environment,authorityFixtures,actor,request} from './fixtures/pn2-native.mjs';
import {verifyMobileNativeCertification} from '../lib/mobile-native-certification.js';
import {sealNativePhoneChallenge,openNativePhoneChallenge} from '../lib/native-phone-challenge-envelope.js';
Object.assign(process.env,environment(['auth','certification','reads']),{PARTICIPANT_PHONE_OTP_RATE_LIMIT_SECRET:'synthetic-only-native-phone-proof-secret-32'});
const id=actor.authUserId,attempt='22222222-2222-4222-8222-222222222222';
function fixture(mode='',native=true){
 const f=authorityFixtures(process.env), store=new Map();let sends=0,verifies=0,signouts=0,consumed=false;
 const authorization={allowed:true,authUserId:id,playerId:actor.playerId,tournamentId:'2026',identifierId:id,identifierRevision:1,phoneE164:'+12025550123',directorEntitlementState:'NONE',directorRole:'NONE',directorScope:'NONE',directorEntitlementRevision:0,directorEntitlementSource:'NONE',directorEntitlementCount:0,directorEntitlementFingerprint:'a'.repeat(32)};
 const ctx={authUserId:id,playerId:mode==='wrong-player'? 'OTHER':actor.playerId,tournament:{id:'2026'},membership:{active:mode!=='deleted'},contextRevision:mode==='stale-context'?2:1};
 const client={auth:{signInWithOtp:async value=>{assert.equal(value.options.shouldCreateUser,false);assert.equal(value.phone,authorization.phoneE164);sends++;return {error:null}},verifyOtp:async value=>{verifies++;assert.equal(value.type,'sms');assert.equal(value.phone,authorization.phoneE164);return mode==='wrong-code'?{error:{code:'otp_expired',status:403}}:{data:{user:{id:mode==='wrong-uuid'?'33333333-3333-4333-8333-333333333333':id},session:{refresh_token:'synthetic-refresh'}}}},getSession:async()=>({data:{session:{access_token:'synthetic-access',refresh_token:mode==='missing-refresh'?null:'synthetic-refresh',user:{id}}}}),signOut:async()=>{signouts++}}};
 const wrap=payload=>({payload});
 const h=createParticipantPhoneLoginHandler({native,nativeAdmission:f.dependencies,cookies:async()=>({get:k=>store.get(k),getAll:()=>[...store.values()],set:(name,value)=>store.set(name,{name,value})}),participantIdentityAuthorityEnvironment:()=>({productionCutoverIdentity:false,participantAuthEnabled:true,resolved:'supabase'}),participantAuthExperienceConfiguration:()=>({smsEnabled:true,captchaRequired:true,rollout:'DESIGNATED'}),verifyParticipantAuthClaims:async()=>({status:'inactive'}),createParticipantAuthServerClient:()=>client,
 beginParticipantPhonePublicRequest:async()=>wrap({allowed:mode!=='rate-limited',code:'PHONE_OTP_RATE_LIMITED'}),authorizeParticipantPhoneLoginRequest:async()=>wrap(['unknown','unverified','revoked'].includes(mode)?{allowed:false}:authorization),authorizeParticipantPhoneLoginProof:async()=>wrap(authorization),beginParticipantPhoneLogin:async()=>wrap({...authorization,attemptId:attempt,expiresAt:new Date(Date.now()+600000).toISOString()}),recordParticipantPhoneLoginSend:async()=>wrap({ok:true}),cancelParticipantPhoneLogin:async()=>wrap({ok:true}),authorizeParticipantPhoneLoginVerification:async()=>{if(consumed||['expired','revoked-after','stale-context','conflict'].includes(mode))return wrap({allowed:false,code:'PHONE_OTP_INVALID_OR_EXPIRED'});consumed=true;return wrap(authorization)},recordParticipantPhoneLoginFailure:async()=>wrap({ok:true}),completeParticipantPhoneLogin:async()=>{if(mode==='completion-throws')throw Error('synthetic');return wrap({ok:mode!=='completion-denies',sameAuthUser:true,sessionEstablished:true,refreshSessionAvailable:true,playerId:actor.playerId,tournamentId:'2026',directorEntitlementPreserved:true,newDirectorEntitlements:0,scoringAuthorizationUnchanged:true,phoneIdentifierUnchanged:true})},reportCanonicalPhoneVerification:async()=>{},certificationDependencies:{readIdentity:async()=>wrap({ok:true,data:ctx})}});
 async function run(input){const req=request('auth/otp/phone',{headers:{origin:'https://baggerinv.com','sec-fetch-site':'same-origin'}});const r=await h.POST(req,input);for(const c of r.cookies.getAll()) {if(c.value)store.set(c.name,c);else store.delete(c.name)}return {r,body:await r.json()}}
 return {run,counts:()=>({sends,verifies,signouts}),store,f,ctx};
}
const start=x=>x.run({action:'request',phone:'+1 (202) 555-0123',captchaToken:'synthetic-captcha-token-at-least-twenty-characters'});
const verify=x=>x.run({action:'verify',attemptId:attempt,token:'123456'});
test('native successful phone claim produces existing certification and minimal Supabase credentials, no browser session cookies',async()=>{
 const x=fixture();const a=await start(x);assert.equal(a.r.status,200);assert.ok(x.store.has('sbi-native-phone-login-proof'));
 const result=await verify(x);assert.equal(result.r.status,200);assert.deepEqual(Object.keys(result.body.data.session).sort(),['accessToken','refreshToken','userId']);assert.equal(result.body.data.session.userId,id);assert.equal(result.body.data.playerId,actor.playerId);
 const token=result.body.data.certification.certificationToken;assert.ok(verifyMobileNativeCertification({...actor,env:process.env,token,productionContext:{runtime:x.f.current,revocationGeneration:'synthetic-generation-1',participant:x.ctx}}));
 assert.equal(x.counts().sends,1);assert.equal(x.counts().verifies,1);assert.equal(x.counts().signouts,0);assert.equal(x.store.size,0);assert.equal(result.r.headers.get('cache-control'),'private, no-store');
});
for(const mode of ['unknown','unverified','revoked'])test(mode+' gets generic acknowledgement, opaque decoy, no send/verify/session',async()=>{const x=fixture(mode),a=await start(x);assert.equal(a.r.status,200);assert.ok(a.body.attemptId);assert.ok(x.store.has('sbi-native-phone-login-proof'));assert.equal(x.counts().sends,0);assert.equal((await verify(x)).body.data,undefined);assert.equal(x.counts().verifies,0)});
for(const mode of ['wrong-code','wrong-uuid','wrong-player','deleted','missing-refresh','expired','revoked-after','stale-context','conflict','completion-denies','completion-throws'])test(mode+' never releases credentials or certification',async()=>{const x=fixture(mode);await start(x);const b=await verify(x);assert.notEqual(b.r.status,200);assert.equal(b.body.data,undefined);if(x.counts().verifies)assert.equal(x.counts().signouts,1)});
test('rate limits deny before provider',async()=>{const x=fixture('rate-limited');assert.equal((await start(x)).r.status,429);assert.equal(x.counts().sends,0)});
test('replay and concurrent verification cannot release a second session',async()=>{const x=fixture();await start(x);const results=await Promise.all([verify(x),verify(x)]);assert.equal(results.filter(r=>r.r.status===200).length,1);assert.equal(x.counts().verifies,1);assert.notEqual((await verify(x)).r.status,200)});
test('native proof confidentiality/tampering/decoy shape',()=>{const k=process.env.PARTICIPANT_PHONE_OTP_RATE_LIMIT_SECRET,a=sealNativePhoneChallenge('existing-signed-proof',k),b=sealNativePhoneChallenge('',k);assert.equal(a.length,b.length);assert.equal(openNativePhoneChallenge(a,k),'existing-signed-proof');assert.equal(openNativePhoneChallenge(b,k),'');assert.throws(()=>openNativePhoneChallenge('Z'+a.slice(1),k));assert.throws(()=>openNativePhoneChallenge(a,'different-secret-at-least-thirty-two-chars'));});
test('web default never gains native credential payload',async()=>{const x=fixture('',false);await start(x);const b=await verify(x);assert.equal(b.r.status,200);assert.equal(b.body.session,'active');assert.equal(b.body.data,undefined);assert.equal(b.body.certification,undefined);assert.equal(b.body.accessToken,undefined)});
test('client cannot inject native completion or arbitrary identity',async()=>{const x=fixture();const b=await x.run({action:'request',phone:'+12025550123',native:true,authUserId:id});assert.equal(b.r.status,400);assert.equal(x.counts().sends,0)});
