import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import * as authority from '../lib/participant-identity-authority.js';import * as host from '../lib/production-cutover-activation-contract.js';import {ready} from './fixtures/pwa-production-phone-env.mjs';
const source=await readFile(new URL('../app/api/participant/auth/session/route.js',import.meta.url),'utf8');const original={...process.env};Object.assign(process.env,ready);test.after(()=>{for(const key in ready){if(key in original)process.env[key]=original[key];else delete process.env[key]}});
function harness({active=true,linked=true}={}){
 const calls=[],cookies=[];const identity={readParticipantIdentityContextForAuth:async input=>{calls.push(['context',input]);return {payload:linked?{ok:true,data:{playerId:'CB01',displayName:'Fixture',tournament:{id:'2026'}}}:{ok:false,code:'PARTICIPANT_CONTEXT_UNAVAILABLE'}}},recordSingleParticipantAuthLogout:async input=>calls.push(['logout',input])};
 const modules={'next/headers':{cookies:async()=>({})},'next/server':{NextResponse:{json:(body,opts={})=>({body,status:opts.status||200,cookies:{set:x=>cookies.push(x)}})}}};
 const forbidden=()=>assert.fail('Production must not use legacy Passport identity');
 const imports=path=>modules[path]||(path.includes('participant-identity-authority')?authority:path.includes('participant-identity-supabase')?identity:path.includes('supabase-auth-server')?{verifyParticipantAuthClaims:async()=>({status:active?'active':'inactive',claims:active?{sub:'11111111-1111-4111-8111-111111111111'}:null}),createParticipantAuthServerClient:()=>({auth:{signOut:async input=>calls.push(['signOut',input])}})}:path.includes('player-passport')?{playerPassportEffectivePlayerId:forbidden,playerPassportTokenFromRequest:forbidden,verifyPlayerPassportSession:forbidden}:path.includes('identity-shadow')?{observeParticipantIdentityShadow:forbidden}:path.includes('scoring-access')?{SCORING_SESSION_COOKIE:'score-cookie',scoringSessionCookie:()=>({value:'',maxAge:0})}:path.includes('cutover-activation')?host:{});
 const code=source.replace(/import\s+\{([\s\S]*?)\}\s+from\s+"([^"]+)";/g,(_,names,path)=>`const {${names}}=imports(${JSON.stringify(path)});`).replaceAll('export ','');return {...new Function('imports',code+';return {GET,DELETE};')(imports),calls,cookies};
}
const request=(method='GET',origin='https://baggerinv.com')=>new Request(origin+'/api/participant/auth/session',{method,headers:{host:new URL(origin).host,origin}});
test('verified email or phone session resolves canonical linked participant without Passport',async()=>{const h=harness();const r=await h.GET(request());assert.equal(r.body.session,'active');assert.equal(r.body.linkedPlayerId,'CB01');assert.equal(r.body.identityAuthority,'supabase');assert.equal(h.calls.filter(c=>c[0]==='context').length,1)});
test('expired session remains inactive without looking up participant',async()=>{const h=harness({active:false});assert.equal((await h.GET(request())).body.session,'inactive');assert.equal(h.calls.length,0)});
test('missing participant linkage cannot become active despite valid Auth claims',async()=>{const h=harness({linked:false});assert.equal((await h.GET(request())).body.session,'inactive')});
test('signout invalidates same Supabase session, records canonical logout and clears scoring cookie',async()=>{const h=harness();const r=await h.DELETE(request('DELETE'));assert.equal(r.body.session,'inactive');assert.deepEqual(h.calls.find(c=>c[0]==='signOut')[1],{scope:'local'});assert.equal(h.calls.find(c=>c[0]==='logout')[1].tournamentId,'2026');assert.equal(h.cookies[0].maxAge,0)});
test('signed-out signout creates no player/link or canonical logout receipt',async()=>{const h=harness({active:false});await h.DELETE(request('DELETE'));assert.equal(h.calls.filter(c=>c[0]==='context'||c[0]==='logout').length,0)});
test('foreign host cannot read or revoke Production session',async()=>{const h=harness();assert.equal((await h.GET(request('GET','https://preview.vercel.app'))).status,404);assert.equal((await h.DELETE(request('DELETE','https://preview.vercel.app'))).status,404);assert.equal(h.calls.length,0)});
