// Proof layer: UNIT. Synthetic artifact data tests the gate, not performance.
import assert from 'node:assert/strict';
import test from 'node:test';
import {evaluatePhase2CPerformance} from '../tools/reliability/phase2c-performance-gate.mjs';
const variants=['none','current_compatible','current_incompatible_consumed','current_incompatible_financial','stale_source','stale_result_binding','superseded_result','multiple_receipts'];
function artifact(mode,kind){return {mode,kind,production:false,environment:'LOCAL_SOCKET_ONLY_POSTGRESQL17',statementTimeoutMs:1000,timeZone:'UTC',executionHead:'a'.repeat(40),baseSha:'b'.repeat(40),fixtureVersion:'unit-only',seed:'unit',phase2MigrationSha256:'c'.repeat(64),candidate:{migrations:[122,123,124].map(n=>({path:`${n}.sql`,sha256:'d'.repeat(64)}))},scales:[1,2,5,10].map(scale=>({scale,counts:{synthetic:scale},archivedCounts:{year:scale},branches:(kind==='common'?['none']:variants).map(variant=>{const n=kind==='common'?1000:30;return {variant,binding:{same:true},samples:n,successCount:n,failureCount:0,p50Ms:1,p95Ms:1,p99Ms:n===1000?1:null,maxMs:1,batches:Array.from({length:kind==='common'?5:3},()=>({valuesMs:Array(n/(kind==='common'?5:3)).fill(1)})),rollbackVerified:true,statementTimeoutMs:1000,nestedSqlExecutions:90,derivedRelationsOnScorePath:[],queryPlanArtifact:'evidence/unit-plan.json'};})}))};}
const inputs=()=>[artifact('baseline','common'),artifact('candidate','common'),artifact('baseline','eligible'),artifact('candidate','eligible')];
test('finite gate accepts complete internally consistent UNIT artifacts',()=>assert.equal(evaluatePhase2CPerformance(...inputs()).status,'PASS'));
test('finite gate rejects missing scales, branches and evidence',()=>{for(const mutate of [a=>a.scales.pop(),a=>a.scales[0].branches.pop(),a=>{delete a.candidate;},a=>{a.scales[0].branches[0].batches.pop();}]){const data=inputs();mutate(data[3]);assert.notEqual(evaluatePhase2CPerformance(...data).status,'PASS');}});
test('finite gate rejects semantic errors, unbounded settings, history work and forged percentile',()=>{for(const mutate of [a=>{a.statementTimeoutMs=0;},a=>{a.production=true;},a=>{a.scales[0].branches[0].failureCount=1;},a=>{a.scales[0].branches[0].derivedRelationsOnScorePath=['calcutta_v1_result_revisions'];},a=>{a.scales[0].branches[0].p99Ms=.5;}]){const data=inputs();mutate(data[1]);assert.equal(evaluatePhase2CPerformance(...data).status,'FAIL');}});
test('finite gate rejects internally consistent material history growth',()=>{const data=inputs(),row=data[1].scales[3].branches[0];for(const b of row.batches)b.valuesMs.fill(20);Object.assign(row,{p50Ms:20,p95Ms:20,p99Ms:20,maxMs:20});const result=evaluatePhase2CPerformance(...data);assert.equal(result.status,'FAIL');assert.ok(result.failures.some(v=>v.endsWith(':history-growth')));});

test('finite gate permits the three retained bounded intent-eligibility reads and rejects other derived relations',()=>{const data=inputs();data[1].scales[0].branches[0].derivedRelationsOnScorePath=['calcutta_v1_current','net_skins_v1_configuration_current','net_skins_v1_configuration_revisions'];assert.equal(evaluatePhase2CPerformance(...data).status,'PASS');data[1].scales[0].branches[0].derivedRelationsOnScorePath.push('calcutta_v1_auction_revisions');assert.equal(evaluatePhase2CPerformance(...data).status,'FAIL');});
