import test from "node:test";import assert from "node:assert/strict";import {americanOdds,ODDS_ENGINE_VERSION,ODDS_LEGACY_PUBLICATION_CONTRACT_VERSION,ODDS_PUBLICATION_CONTRACT_VERSION,ODDS_SIMULATION_SEED_VERSION,rankPlayerOddsRows,simulatedPlayerPointAllocations,simulateNassauMatchPoints,simulateTournamentOdds,validateOpeningMatchups} from "../lib/tournament-odds.js";
test("converts probabilities to American odds",()=>{assert.equal(americanOdds(50),"+100");assert.equal(americanOdds(40),"+150");assert.equal(americanOdds(25),"+300");assert.equal(americanOdds(60),"-150");});
test("requires complete Round 1 and Round 2 matchups before publishing",()=>{const empty=validateOpeningMatchups({matches:[]},2026);assert.equal(empty.ready,false);assert.equal(empty.roundReports[0].status,"FAIL");const match=(round)=>({Year:2026,Round:round,Format:"BB",Match:1,"Team 1 Player 1":"A","Team 1 Player 2":"B","Team 2 Player 1":"C","Team 2 Player 2":"D"});const handicaps=[...["A","B"].map(id=>({Year:2026,"Team Side":"Team 1","Player ID":id})),...["C","D"].map(id=>({Year:2026,"Team Side":"Team 2","Player ID":id}))];const complete=validateOpeningMatchups({matches:[match(1),match(2)],handicaps,projectionMatchSource:"Live Matches"},2026);assert.equal(complete.ready,true);assert.deepEqual(complete.roundReports.map(row=>row.status),["PASS","PASS"]);});
test("reports the exact worksheet row, match, and missing pairing position",()=>{const matches=[{Year:2026,Round:1,Format:"BB",Match:1,"Team 1 Player 1":"A","Team 1 Player 2":"B","Team 2 Player 1":"C"}];const handicaps=[...["A","B"].map(id=>({Year:2026,"Team Side":"Team 1","Player ID":id})),...["C","D"].map(id=>({Year:2026,"Team Side":"Team 2","Player ID":id}))];const status=validateOpeningMatchups({matches,handicaps,projectionMatchSource:"Live Matches"},2026);assert.equal(status.ready,false);assert.equal(status.firstFailure,"Live Matches row 2, Match 1: Team 2 Player 2 is blank.");assert.deepEqual(status.roundReports[0].missingPlayers,["D"]);});
test("a complete tournament simulation always allocates all 72 points",()=>{const ids1=Array.from({length:12},(_,i)=>`A${i}`),ids2=Array.from({length:12},(_,i)=>`B${i}`);const handicaps=[...ids1.map(id=>({Year:2026,"Team Side":"Team 1","Player ID":id,"Tournament Handicap":10})),...ids2.map(id=>({Year:2026,"Team Side":"Team 2","Player ID":id,"Tournament Handicap":10}))];const matches=[];for(const round of [1,2])for(let i=0;i<6;i++)matches.push({Year:2026,Round:round,Format:round===1?"BB":"SC","Team 1 Player 1":ids1[i*2],"Team 1 Player 2":ids1[i*2+1],"Team 2 Player 1":ids2[i*2],"Team 2 Player 2":ids2[i*2+1]});const sheets={matches,handicaps,tournamentRules:[1,2,3].map(round=>({Year:2026,Round:`Round ${round}`,"Points Available":3}))};const result=simulateTournamentOdds({sheets,iterations:100});assert.equal(result.totalPointsAvailable,72);assert.equal(Number((result.teams[0].expectedPoints+result.teams[1].expectedPoints).toFixed(2)),72);});
test("future Nassau matches distribute front, back, and overall points without changing the configured total",()=>{const draws=[.1,.55,.95];let index=0;const [one,two]=simulateNassauMatchPoints({pointsAvailable:3,teamOneWinProbability:.5,tieProbability:.1,random:()=>draws[index++]});assert.equal(one,1.5);assert.equal(two,1.5);assert.equal(one+two,3);});
test("future Nassau matches support realistic half-point distributions",()=>{const possible=new Set();for(let mask=0;mask<27;mask++){let value=mask;const draws=[];for(let segment=0;segment<3;segment++){draws.push([.1,.55,.9][value%3]);value=Math.floor(value/3);}let index=0;const [one,two]=simulateNassauMatchPoints({pointsAvailable:3,teamOneWinProbability:.5,tieProbability:.1,random:()=>draws[index++]});possible.add(one);assert.equal(one+two,3);}assert.deepEqual([...possible].sort((a,b)=>a-b),[0,.5,1,1.5,2,2.5,3]);});
test("team-format points split equally between partners for every approved example",()=>{for(const [one,two,expectedOne,expectedTwo] of [[3,0,1.5,0],[2,1,1,.5],[2.5,.5,1.25,.25],[1.5,1.5,.75,.75]]){const allocations=simulatedPlayerPointAllocations({format:"BB",teamOneIds:["A1","A2"],teamTwoIds:["B1","B2"],teamOnePoints:one,teamTwoPoints:two});assert.deepEqual(allocations[0].map(row=>row.points),[expectedOne,expectedOne]);assert.deepEqual(allocations[1].map(row=>row.points),[expectedTwo,expectedTwo]);assert.equal(allocations.flat().reduce((sum,row)=>sum+row.points,0),3);}});
test("Singles points remain individual without partner splitting",()=>{const allocations=simulatedPlayerPointAllocations({format:"SI",teamOneIds:["A1"],teamTwoIds:["B1"],teamOnePoints:2,teamTwoPoints:1});assert.deepEqual(allocations,[[{id:"A1",points:2}],[{id:"B1",points:1}]]);});
test("tied points leaders divide one mutually exclusive championship outcome",()=>{const handicaps=[...['A1','A2'].map(id=>({Year:2026,'Team Side':'Team 1','Player ID':id})),...['B1','B2'].map(id=>({Year:2026,'Team Side':'Team 2','Player ID':id}))];const teamMatch=(round,format)=>({Year:2026,Round:round,Format:format,'Team 1 Player 1':'A1','Team 1 Player 2':'A2','Team 2 Player 1':'B1','Team 2 Player 2':'B2','Team 1 Points':1.5,'Team 2 Points':1.5});const matches=[teamMatch(1,'BB'),teamMatch(2,'SC'),{Year:2026,Round:3,Format:'SI','Team 1 Player 1':'A1','Team 2 Player 1':'B1','Team 1 Points':1.5,'Team 2 Points':1.5},{Year:2026,Round:3,Format:'SI','Team 1 Player 1':'A2','Team 2 Player 1':'B2','Team 1 Points':1.5,'Team 2 Points':1.5}];const sheets={matches,handicaps,tournamentRules:[1,2,3].map(round=>({Year:2026,Round:`Round ${round}`,'Points Available':3}))};const result=simulateTournamentOdds({sheets,phase:'Final Results',iterations:10});assert.deepEqual(result.players.map(player=>player.probability),[25,25,25,25]);assert.deepEqual(result.players.map(player=>player.rank),[1,2,3,4]);assert.equal(result.players.reduce((sum,player)=>sum+player.probability,0),100);assert.equal(result.engineVersion,ODDS_ENGINE_VERSION);assert.equal(result.publicationContractVersion,ODDS_PUBLICATION_CONTRACT_VERSION);assert.equal(result.deterministicSeed,`2026|Final Results|${ODDS_SIMULATION_SEED_VERSION}`);});

test("prospective player ranking uses raw probability and preserves the deterministic source order only for genuine ties",()=>{const rows=[
  {id:"PN",name:"Patrick Noonan",rawProbability:0},{id:"RM",name:"Robert Murphy",rawProbability:0},
  {id:"BC",name:"Brenan Cavanaugh",rawProbability:.36},{id:"JP",name:"Jason Powell",rawProbability:.41},{id:"JS",name:"Jack Samis",rawProbability:.44},
  {id:"BA",name:"Brian Atkinson",rawProbability:.26},{id:"CP",name:"Chase Patterson",rawProbability:.29},{id:"MS",name:"Memo Saldana",rawProbability:.32},{id:"WO",name:"Will Oliver",rawProbability:.34},
].map(row=>({...row,probability:+row.rawProbability.toFixed(1),americanOdds:americanOdds(row.rawProbability)}));const ranked=rankPlayerOddsRows(rows);
assert.deepEqual(ranked.filter(row=>row.probability===.4).map(row=>row.name),["Jack Samis","Jason Powell","Brenan Cavanaugh"]);
assert.deepEqual(ranked.filter(row=>row.probability===.3).map(row=>row.name),["Will Oliver","Memo Saldana","Chase Patterson","Brian Atkinson"]);
assert.deepEqual(ranked.filter(row=>row.rawProbability===0).map(row=>row.name),["Patrick Noonan","Robert Murphy"]);
assert.deepEqual(ranked.map(row=>row.rank),Array.from({length:ranked.length},(_,index)=>index+1));
for(const row of ranked)assert.equal(row.americanOdds,americanOdds(row.rawProbability));});

test("historical odds-v2-nassau payloads remain reproducible without prospective fields",()=>{const handicaps=[{Year:2026,"Team Side":"Team 1","Player ID":"A"},{Year:2026,"Team Side":"Team 2","Player ID":"B"}];const matches=[1,2,3].map(round=>({Year:2026,Round:round,Format:"SI","Team 1 Player 1":"A","Team 2 Player 1":"B","Team 1 Points":1.5,"Team 2 Points":1.5}));const sheets={matches,handicaps,tournamentRules:[1,2,3].map(round=>({Year:2026,Round:round,"Points Available":3}))};const legacy=simulateTournamentOdds({sheets,phase:"Final Results",iterations:4,contractVersion:ODDS_LEGACY_PUBLICATION_CONTRACT_VERSION});const current=simulateTournamentOdds({sheets,phase:"Final Results",iterations:4});assert.equal(legacy.engineVersion,undefined);assert.equal(legacy.publicationContractVersion,undefined);assert.equal(legacy.deterministicSeed,undefined);assert.equal(legacy.players[0].rawProbability,undefined);assert.equal(legacy.players[0].rank,undefined);assert.deepEqual(legacy.players,current.players.map(({rawProbability:_rawProbability,rank:_rank,...row})=>row));assert.deepEqual(legacy.teams,current.teams.map(({rawProbability:_rawProbability,...row})=>row));});
