import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {approvedSmsHook,approvedVerifyFeedback,smsHookConfiguration} from '../lib/production-approved-sms-hook.js';
const uid='00000000-0000-4000-8000-000000000001',aid='10000000-0000-4000-8000-000000000001',sid='VE'+'c'.repeat(32),old='VE'+'d'.repeat(32),phone='+12025550123';
const env={VERCEL_ENV:'production',PARTICIPANT_SMS_SEND_HOOK_ENABLED:'true',PARTICIPANT_SMS_AUTH_ENABLED:'true',SUPABASE_SEND_SMS_HOOK_SECRET:'whsec_'+Buffer.alloc(32,7).toString('base64'),TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_VERIFY_SERVICE_SID:'VA'+'b'.repeat(32),TWILIO_AUTH_TOKEN:'fixture-only'};
function request(code='654321') {const now=Date.now(),stamp=String(Math.floor(now/1000));const raw=JSON.stringify({user:{id:uid,new_phone:phone},sms:{phone,otp:code}}),headers=new Headers({'webhook-id':'evt-fixture','webhook-timestamp':stamp});headers.set('webhook-signature','v1,'+createHmac('sha256',smsHookConfiguration(env).key).update(`evt-fixture.${stamp}.${raw}`).digest('base64'));return {raw,headers,env,now};}
function receipt(id,status,extra={}){return {sid:id,status,to:phone,service_sid:env.TWILIO_VERIFY_SERVICE_SID,account_sid:env.TWILIO_ACCOUNT_SID,channel:'sms',...extra};}
function fixture({resend=false,cancelError=false,cancelBody=null,sendBody=null,deny=false,feedback=false,feedbackError=false,claimExtra={}}={}){
 let claimed=false,state;const calls=[],network=[];
 const rpc=async x=>{calls.push(x);if(deny)throw Error('DENIED');if(x.action==='claim'){if(claimed)throw Error('REPLAY');claimed=true;return {ok:true,state:'CLAIMED',attemptId:aid,priorVerificationSid:resend?old:null,verificationSid:sid,verifyServiceSid:env.TWILIO_VERIFY_SERVICE_SID,phoneE164:phone,...claimExtra};}state=x.action.toUpperCase();return {ok:true,state,attemptId:aid};};
 const fetchImpl=async(url,o)=>{network.push({url,form:Object.fromEntries(new URLSearchParams(o.body))});assert.equal(o.redirect,'error');if(url.endsWith('/'+old)){if(cancelError)throw Error('timeout');return {status:200,json:async()=>cancelBody||receipt(old,'canceled')};}if(feedback){if(feedbackError)throw Error('timeout');return{status:200,json:async()=>receipt(sid,'approved')};}return {status:201,json:async()=>sendBody||receipt(sid,'pending')};};
 return{rpc,fetchImpl,calls,network,state:()=>state};
}
test('CustomCode is byte-for-byte Supabase code; not generated/returned/stored in receipt',async()=>{const f=fixture();assert.deepEqual(await approvedSmsHook(request(),f),{});assert.equal(f.network[0].form.CustomCode,'654321');assert.deepEqual(Object.keys(f.network[0].form).sort(),['Channel','CustomCode','To']);assert.equal(f.calls[1].verification_sid,sid);assert.ok(!JSON.stringify(f.calls).includes('654321'));});
test('resend cancels exact prior VE before sending different Supabase code',async()=>{const f=fixture({resend:true});await approvedSmsHook(request('123456'),f);assert.equal(f.network.length,2);assert.ok(f.network[0].url.endsWith('/'+old));assert.deepEqual(f.network[0].form,{Status:'canceled'});assert.equal(f.network[1].form.CustomCode,'123456');});
for(const opts of [{cancelError:true},{cancelBody:receipt(old,'pending')},{cancelBody:receipt(sid,'canceled')},{cancelBody:receipt(old,'canceled',{to:'+12025550124'})},{claimExtra:{verifyServiceSid:'VA'+'f'.repeat(32)}}])test('uncertain/wrong cancellation fails closed before resend '+JSON.stringify(opts),async()=>{const f=fixture({resend:true,...opts});await assert.rejects(approvedSmsHook(request(),f));assert.ok(!f.network.some(x=>'CustomCode' in x.form));assert.equal(f.state(),'UNCERTAIN');});
test('duplicate old verification receipt cannot certify a new code',async()=>{const f=fixture({resend:true,sendBody:receipt(old,'pending')});await assert.rejects(approvedSmsHook(request(),f));assert.equal(f.state(),'UNCERTAIN');});
for(const body of [receipt(sid,'approved'),receipt(sid,'expired'),receipt(sid,'failed'),receipt(sid,'pending',{service_sid:'VA'+'f'.repeat(32)}),receipt(sid,'pending',{channel:'call'})])test('only exact pending receipt is accepted '+body.status+body.channel,async()=>{const f=fixture({sendBody:body});await assert.rejects(approvedSmsHook(request(),f));assert.equal(f.state(),'UNCERTAIN');});
test('server receipt is not authentication',async()=>{const f=fixture();await approvedSmsHook(request(),f);assert.deepEqual(f.calls.map(x=>x.action),['claim','sent']);assert.ok(!f.network.some(x=>x.url.includes('VerificationCheck')));});
test('feedback requires canonical DB claim before provider call',async()=>{const f=fixture({feedback:true,deny:true});await assert.rejects(approvedVerifyFeedback({attemptId:aid,authUserId:uid,env},f));assert.equal(f.network.length,0);});
test('successful feedback uses exact VE and no code; one-shot',async()=>{const f=fixture({feedback:true});assert.deepEqual(await approvedVerifyFeedback({attemptId:aid,authUserId:uid,env},f),{state:'ACKNOWLEDGED'});assert.deepEqual(f.network[0].form,{Status:'approved'});assert.ok(f.network[0].url.endsWith('/'+sid));await assert.rejects(approvedVerifyFeedback({attemptId:aid,authUserId:uid,env},f));assert.equal(f.network.length,1);});
test('feedback timeout records uncertainty without authentication fallback or retry',async()=>{const f=fixture({feedback:true,feedbackError:true});assert.deepEqual(await approvedVerifyFeedback({attemptId:aid,authUserId:uid,env},f),{state:'UNCERTAIN'});assert.equal(f.network.length,1);});
test('wrong feedback attempt denied',async()=>{const f=fixture({feedback:true,claimExtra:{attemptId:uid}});await assert.rejects(approvedVerifyFeedback({attemptId:aid,authUserId:uid,env},f));assert.equal(f.network.length,0);});
test('MG service cannot replace VA Verify config',()=>assert.throws(()=>smsHookConfiguration({...env,TWILIO_VERIFY_SERVICE_SID:'MG'+'b'.repeat(32)})));
test('routes report feedback only after canonical completion; no client-selected receipt',()=>{const e=readFileSync(new URL('../app/api/participant/auth/phone-enrollment/route.js',import.meta.url),'utf8'),l=readFileSync(new URL('../app/api/participant/auth/phone/route.js',import.meta.url),'utf8');assert.ok(e.indexOf('await reportCanonicalPhoneVerification')>e.indexOf('await productionPhoneEnrollment'));assert.ok(l.indexOf('await reportCanonicalPhoneVerification')>l.indexOf('completion.ok !== true'));assert.match(e,/input.action==='verify'&&result.status==='VERIFIED'&&result.sameAuthUser===true/);});

import {assertParticipantIdentityAdministrativeEnvironment} from '../lib/participant-identity-authority.js';
import {ready as productionEnv} from './fixtures/pwa-production-phone-env.mjs';
test('feedback uses the real Production operation allowlist; arbitrary feedback RPC denied',()=>{
 assert.doesNotThrow(()=>assertParticipantIdentityAdministrativeEnvironment(productionEnv,{operation:'production_participant_phone_feedback_v1'}));
 assert.throws(()=>assertParticipantIdentityAdministrativeEnvironment(productionEnv,{operation:'production_participant_phone_feedback_unreviewed'}));
});
